- package.json
Will pull mod-orders into the "snapshot" build. Towards FOLIO-1531.
> Require "orders" Okapi interface.

- src/routes/Main.js
This was added before for new mod-orders API /orders, and now this API is changed, so kind of reverting. 
Also, I noticed that comments no longer exist in purchase_order, I believe it's `notes` now, so displaying them in the list
> UIOR-7 remove hierarchy to show list of composite_purchase_orders

- src/settings/index.js
https://github.com/folio-org/stripes-core/pull/489
Retrieving the `intl` object from `this.context.intl` or the `stripes` god object (`stripes.intl`) is a deprecated pattern.
Use `<FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` as often as possible, only falling back to `formatMessage()`, `formatDate()`, and `formatTime()` (accompanied by `injectIntl()`) when a bare string is absolutely necessary.
> Replace stripes.intl.formatMessage with FormattedMessage

- src/components/POLine/Vendor/VendorForm.js
- src/components/Utils/Validate.js
- translations/ui-orders/en.json
Purpose:
Vendor Ref Number and Vendor Ref Type are paired fields.
If Vendor Ref Number (free text field) is filled in, then Vendor Ref Type should be required.
If Vendor Ref Number is not filled in, then Vendor Ref Type should not be required.
> UIOR-83 Add PO Line - Vendor Ref Type required field

- src/settings/ClosingReasonsForm.js
Overview: Save and remove button are overlapping
How to reproduce:
Open settings
Choose orders settings
Choose "Closing Purchase Order Reasons"
Click "Add"
Actual Result:
'Save' button and 'Remove' button are overlapping
Expected Result:
There should be some padding between the buttons
https://issues.folio.org/browse/UIOR-99
> UIOR-99 Settings: Padding issue when adding a "Reason for closure"

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/const.js
- src/routes/Main.js
- src/settings/POLinesLimitForm.js
- test/bigtest/network/config.js
* in Settings for PO Lines limit show placeholder as 1 instead of 999;
* in Orders list don't show alert with errors if clicked on order with invalid id;
* in Create PO Line fill po_line_number as _(orderNumber)-(orderLinesCount+1)_;
* in Create/Edit PO Line change validation of po_line_number to simple required;
* in Edit Order fetch fresh generated PO Number from orderNumber API;
* in Orders List added _columnWidths_ property to SearchAndSort to make po_number column wider;
* in Orders List removed unused code for use filtering on back-end, since API don't support it for now.
> UIOR-117 several fixes

- src/components/LayerCollection/LayerPOLine.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/FilterConfig.js
- src/components/Utils/orderResource.js
- src/routes/Main.js
- test/bigtest/interactors/orders.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/order.js
- test/bigtest/tests/details-order-test.js
FOLIO naming conventions for schemas dictate that camelCase is used for field names instead of under_score notation.
https://issues.folio.org/browse/UIOR-115
Should be merged after
https://issues.folio.org/browse/MODORDERS-130
https://github.com/folio-org/acq-models/pull/80
https://github.com/folio-org/mod-orders-storage/pull/73
https://github.com/folio-org/mod-orders/pull/84
> UIOR-115 Update the po_number schema to use camelCase

- package.json
Fix UIOR-104 Orders: No Functioning Permission for Access to Orders App
Some permissions were added to mod-orders description.
https://issues.folio.org/browse/UIOR-104
I've added missing permissions to package.json …
> UIOR-104 add missing permissions to ui-orders package.json

- test/bigtest/tests/line-edit-test.js
Mistakenly pushed `.pause` on test in previous PR
> UIOR-121 remove pause

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/line-number-test.js
UIOR-111 -  Adjustments to PO Line number field on create/edit PO Line forms
It's required to call and prepopulate line number. And to disable it for editing.
https://issues.folio.org/browse/UIOR-111
On form did mount it's checked if line is new and call api to prepopulate line number field. …
> UIOR-111 call po line number sequence API

- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/util.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/network/config.js
- test/bigtest/tests/create-order-test.js
- translations/ui-orders/en.json
To provide ability de-select suffix or prefix
https://issues.folio.org/browse/UIOR-119
Add empty option to suffixes or prefixes. …
> UIOR-119 Once a prefix or suffix is selected you cannot remove them

- src/components/POLine/POLineDetails/POLineDetailsForm.js
https://issues.folio.org/browse/UIOR-111
It just seems unnecessary to have it disabled on the screen. When editing it could be valuable to see it as there will be a number in there but during creation it seems redundant. …
> UIOR-111 remove PO Line number from Create form

- CHANGELOG.md
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingLinks.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/index.js
- src/index.js
- test/bigtest/interactors/receiving-history-page.js
- test/bigtest/tests/receiving-history-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIREC-14
Button Group to help User navigate between Receiving Items and History
Several React Router routes were created to support navigation. …
> UIREC-14 Receive History access button

- src/components/Receiving/ReceivingHistory.js
* Render Confirmation modal only after Receive button is clicked.
* Remove button stays enabled if line is unchecked.
https://issues.folio.org/browse/UIREC-21 …
> UIREC-21 fix warning and Remove button disabling

- .eslintrc
- src/components/PurchaseOrder/PO.js
- test/bigtest/.eslintrc
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/details-order-test.js
To improve UX instead of error messages on calling back-en for Add PO Line it's better to disable button leading to Add PO Line form.
https://issues.folio.org/browse/UIOR-144 …
> UIOR-144 disable Add line button for non-pending orders

- src/components/Receiving/ItemDetails.js
- src/components/Receiving/ReceivingList.js
- test/bigtest/interactors/piece-details-modal.js
- test/bigtest/tests/piece-details-test.js
It's a fix to provide selected lines correctly into Piece Details modal
https://issues.folio.org/browse/UIOR-154
in setState() we should never mutate objects, only set a new one, so React can see that change is happened. …
> UIOR-154 fix checking lines to receive

- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/routes/Main.js
To fix background coloring of rows using MCL components
https://issues.folio.org/browse/STCOM-486
In `columnWidths` object we shouldn't use string values, since table width will not be calculated properly, more details in the ticket's comments. …
> STCOM-486 fix columns widths

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineForm.js
This is the fix of regression.
There is a bug when form component of PO Line is not refreshed on form field change. It confuses a user, since on any refresh accordions could be re-arranged.
https://issues.folio.org/browse/UIOR-128
Apparently we have to pass down `connectedSource` property to get all stored form values in sync
Ideally all of the PRs …
> UIOR-128 E-resource and Physical resource accordions don't display

- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
Basically at some point we've lost a prop that caused re-render.
`connectedSource` makes form re-render, it generates inside SearchAndSort component …
> fix PO Form re-render

- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/util.js
- test/bigtest/tests/receiving-list-test.js
User should be able to view receiving history for Closed order
https://issues.folio.org/browse/UIOR-226
Receiving or checkIn button is visible if order open or close.
Check `workflowStatus` to redirect the user to items or history. …
> UIOR-226 Access Receiving/Checkin history for closed orders

- src/common/POLFields/VendorFields/FieldVendorAccountNumber.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/POLineVendorForm.js
- If a vendor is assigned in the template, and accounts are in the vendor record, the Account field should display the accounts associated with that vendor, but only allow 1 to be selected
- If a vendor is assigned in the template, and account numbers are NOT available in the vendor record, the Account field should be a free-text field
- If a vendor is NOT assigned in the template, the Account field should be a free-text field
- …
> UIOR-379 Template fix: Account number field

- src/components/POLine/Item/ItemForm.js
If the user has NOT yet used the instance lookup, they should not see the "Not connected" message above the title field. Only after an instance has been connected should it be possible for the "Not connected" message to display.
https://issues.folio.org/browse/UIOR-451
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> UIOR-451 Item details: Title

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/util.js
If `isPackage=true` plus does not appear. The instance is not connected to a POL that represents a package. Titles created for that package in receiving can link to instances.
https://issues.folio.org/browse/UIOR-502 …
> UIOR-502 Plus action appears when POL isPackage

- CHANGELOG.md
- package.json
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/getPOActionMenu.js
'Check-in Items' permission still shows in permissions list
https://issues.folio.org/browse/UIOR-537 …
> UIOR-537 'Check-in Items' permission still shows in permissions list

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Item/util.js
- src/components/POLine/Item/util.test.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/POLine/line-edit-capture-inventure-uuid-test.js
Basically, the initial functionality were implemented in this commit year ago
https://github.com/folio-org/ui-orders/blob/ba587fe632d58c3b41ceebb8fcd0fe79133d0b04/src/components/POLine/Item/ItemForm.js#L124
after that it was broken here 10 months ago
https://github.com/folio-org/ui-orders/blob/571b737a6ef191402c68074d4818b662c4313cac/src/components/POLine/Item/ItemForm.js#L121
and more broken logic were committed here
https://github.com/folio-org/ui-orders/blob/5477c1faae9d0c106965613f778b180ffbf53930/src/components/POLine/Item/util.js#L48 
https://issues.folio.org/browse/UIOR-552
There was wrong approach on comparing data. It was always involving `initialValues`, that didn't work right when user edit PO Line and select another instance. `getInventoryData` were always merging state of …
> UIOR-552 fix to loose and set up again link to instance

- CHANGELOG.md
- package.json
- src/components/POLine/POLineAgreementLines/POLineAgreementLines.js
- src/components/POLine/POLineAgreementLines/POLineAgreementLines.test.js
fix and release
https://issues.folio.org/browse/UIOR-627 …
> UIOR-627 fix dsiplaying of agr lines

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
Do not call `list.forEach` if `list` is null. [Line 104 sets `locations`
to a possibly null value](https://github.com/folio-org/ui-orders/blame/8cd095498aca31589d147a32e888073f0d4b72e7/src/components/POLine/Item/ItemForm.js#L101-L116):
```
const locations = formValues?.locations;
```
and therefore we must validate it before calling methods on it.
This should help unblock #1337.
Refs [UIOR-997](https://issues.folio.org/browse/UIOR-997)
> UIOR-997 do not iterate if locations is null

- CHANGELOG.md
- package.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
ui-orders uses only the holdings-storage interface, not the other two.
ui-orders is not affected because the incompatible change is in the DELETE all APIs only.
Only the okapiInterfaces need to be bumped in package.json.
> UIOR-1017: Support holdings-storage 6.0

- CHANGELOG.md
- package.json
Add version 12.0 to the list of supported inventory interface versions.
DELETE /inventory/instances and DELETE /inventory/items have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-orders doesn't need any code change because it doesn't use these two DELETE APIs.
> UIOR-1020: Support inventory 12.0 in okapiInterfaces

- CHANGELOG.md
- src/components/POLine/Cost/CostForm.js
- src/components/Utils/parseNumber.js
https://issues.folio.org/browse/UIOR-1029
Cleared cost fields return an empty string as value, which is confusing since a number is expected 
Update parse function to return `null` instead of `""` (empty string) for PO Line cost fields with `number` type.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> UIOR-1029 Blanking 'Quantity physical' or 'Quantity electronic' from order template sets property to empty string

- CHANGELOG.md
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersList.test.js
- src/common/utils/index.js
- src/common/utils/omitFieldArraysAsyncErrors.js
- src/common/utils/omitFieldArraysAsyncErrors.test.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/components/POLine/const.js
- src/components/PurchaseOrder/PO.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-1038
- Update permission name in shortcut handlers
- Update accordions configs
- For `POLineForm` and `OrderTenplatesEditor` forms omit async field-arrays errors, that prevents toggle accordions - there is an [issue](https://github.com/final-form/react-final-form-arrays/issues/176) with async validation of `FieldArray` itself. Async validation of `FundDistributionFieldsFinal` field-array delegates error state to [hidden field](https://github.com/folio-org/stripes-acq-components/blob/master/lib/FundDistribution/FundDistributionFields/FundDistributionFieldsFinal.js#L249).
- Does this introduce breaking …
> UIOR-1038 Some shortcut keys do not work in the "Orders" app

- CHANGELOG.md
- src/components/POLine/Item/BreakInstanceConnectionModal/BreakInstanceConnectionModal.js
- src/components/POLine/Item/BreakInstanceConnectionModal/BreakInstanceConnectionModal.test.js
- src/components/POLine/Item/BreakInstanceConnectionModal/index.js
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemForm.test.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Item/util.js
- translations/ui-orders/en.json
Show confirmation modal before breaking instance connection and applying change to instance related field
https://issues.folio.org/browse/UIOR-1047
- add `<BreakInstanceConnectionModal />` component
- update handlers for fields changing and deletion (add ability to handle changes asynchronously)
- use JS Promise `resolve` and `reject` as modal `Confirm` and `Cancel` handlers accordingly for declarative processing
- unit tests
- …
> UIOR-1047 Add confirmation modal - Break instance connection

- CHANGELOG.md
- src/components/POLine/POLineVersionView/EresourcesVersionView/EresourcesVersionView.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.test.js
- src/components/POLine/utils.js
- src/components/PurchaseOrder/POVersionView/PODetailsVersionView/PODetailsVersionView.js
- src/components/PurchaseOrder/POVersionView/SummaryVersionView/SummaryVersionView.js
- src/components/PurchaseOrder/POVersionView/SummaryVersionView/SummaryVersionView.test.js
https://issues.folio.org/browse/UIOR-1070
https://issues.folio.org/browse/UIOR-1071
https://issues.folio.org/browse/UIOR-1072
- update field name of `Manual` checkbox (UIOR-1070)
- use common component to format `Approval date` as a date (UIOR-1071)
- fix displayed values for `Reason for closure` and `Notes on closure` fields (UIOR-1072)
- fix displayed values for `Activation status` and `URL` fields (e-resources)
- fix highlights of locations component
- Do JIRAs exist to …
> UIOR-1070 UIOR-1071 UIOR-1072 Fix displayed values on order version history view

- CHANGELOG.md
- src/common/hooks/index.js
- src/common/hooks/useAcqMethod/index.js
- src/common/hooks/useAcqMethod/useAcqMethod.js
- src/common/hooks/useAcqMethod/useAcqMethod.test.js
- src/common/hooks/useAcqMethods/useAcqMethods.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetails.test.js
https://issues.folio.org/browse/UIOR-1103
- exclude getting a single acquisition method from the `useAcqMethods` hook in `useAcqMethod` to keep single responsibility;
- check if the PO Line `acquisitionMethod` and `checkinItems` values are defined for displaying them in the `Acquisition method` and `Receiving workflow` fields respectively.
<details><summary>Empty fields</summary>
<p>
</p>
</details>
<details><summary>Populated fields</summary>
<p>
</p>
</details>
- Do JIRAs …
> UIOR-1103 Some values are displayed by default in 'View' mode for empty fields in the order template

- CHANGELOG.md
- src/components/POLine/Vendor/VendorForm.js
- src/components/POLine/Vendor/VendorForm.test.js
- src/components/POLine/const.js
- translations/ui-orders/en.json
[UIOR-1142](https://issues.folio.org/browse/UIOR-1142) - POL - Display only active account numbers in dropdown list
https://github.com/folio-org/ui-orders/assets/116072773/ac059319-c632-4527-b41b-745ac91a205d
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UIOR-1142: POL - Display only active account numbers in dropdown list

- CHANGELOG.md
- src/common/constants/constants.js
- src/common/hooks/index.js
- src/common/hooks/useInstance/useInstance.js
- src/common/hooks/useTenantKy/index.js
- src/common/hooks/useTenantKy/useTenantKy.js
- src/common/hooks/useTenantKy/useTenantKy.test.js
- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-1159
https://issues.folio.org/browse/UIIN-2614
In order to support creating an order from an instance in the "consortium" mode, a PO line form must have the ability to fetch instance data in the specific tenant (actually the central tenant for shared instances).
- Implement a hook to make requests to the specific tenant;
- Fetch an instance data based on `instanceTenantId` location state value, provided by the inventory app.
https://github.com/folio-org/ui-orders/assets/88109087/ad409abd-aaea-4ada-9b54-b8be200a256d
If there are breaking changes, please **STOP** …
> UIOR-1159 Use a provided `tenantId` when loading an instance in a PO line form

- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPO.test.js
https://issues.folio.org/browse/UIOR-1159
This PR is for the missed part of #1511 
There are two ways of navigating to the orders app from the inventory (when creating an order from an instance): to the PO form and to the PO Line form. In both cases, we should handle the provided `instanceTenantId`. The previous PR (#1511) covers only the second way. So we still need to provide `instanseTenantId` to the PO line form, but now from PO form.
Pass the `instanceTenantId` value from inventory to PO line form through PO form.
https://github.com/folio-org/ui-orders/assets/88109087/d9ff8a85-8df1-453d-b793-1df47c14c15a
- Does this introduce …
> UIOR-1159 Provide 'instanceTenantId' from the PO form to PO line form

- CHANGELOG.md
- src/PrintOrder/PrintOrder.js
https://issues.folio.org/browse/UIOR-1173 …
> UIOR-1173 Preview contains blank page when trying to print an order

- CHANGELOG.md
- src/components/POLine/Vendor/VendorForm.js
https://issues.folio.org/browse/UIOR-1174 …
> UIOR-1174 Do not disable account numbers having only one account available

- package.json
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemForm.test.js
[UIOR-1078](https://issues.folio.org/browse/UIOR-1078) - enable subscription to filed when workflow status is `open`
https://github.com/folio-org/ui-orders/assets/116072773/c14098e2-9afd-4d58-8ab0-047766fa0034
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> UIOR-1078: enable subscription to filed when workflow status is open

- CHANGELOG.md
- src/common/POLFields/DetailsFields/FieldClaimingActive.js
- src/common/POLFields/DetailsFields/FieldClaimingActive.test.js
- src/common/POLFields/DetailsFields/FieldClaimingInterval.js
- src/common/POLFields/DetailsFields/FieldClaimingInterval.test.js
- src/common/POLFields/index.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetails.test.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-396
https://issues.folio.org/browse/UIOR-397
Implement new components for viewing and editing the "Claiming active" and "Claiming interval" fields in PO Line details.
https://github.com/folio-org/ui-orders/assets/88109087/a75c54e9-0581-41c4-a1d2-4325413f67d7 …
> UIOR-396 UIOR-397 Add 'claiming active' and 'claiming interval' fields

- CHANGELOG.md
- src/components/POLine/LineLinkedInstances/hooks/useLinkedInstances/useLinkedInstances.js
https://issues.folio.org/browse/UIOR-1181
Some queries triggered by UI do not use DB indexes during Get Order/Get Po Line/ Open Oder/ Receive order flow. Need to optimize them to improve performance.
```
14:20:12 [352325/orders;830317/orders-storage] [diku] [c88a8880-f8ec-55c5-a808-14cfb0744108] [mod_orders_storage] WARN  CQL2PgJSON           Doing FT search without index for titles.jsonb->>'instanceId', CQL >>> SQL: instanceId = "" >>> titles.jsonb->>'instanceId' ~ '' 
```
Delete redundant `instanceId=""`.
- What other …
> UIOR-1181 Optimize linked instances query to improve performance

- src/components/POLine/POLineForm.js
[UIOR-1148](https://issues.folio.org/browse/UIOR-1148) - prevent donors auto-populate with fund distributions'(donorOrganizationIds) on edit mode
https://github.com/folio-org/ui-orders/assets/116072773/ac3bd749-dc4c-4cb1-9e27-189a4ca953ec …
> fix: donorOrganizationIds auto populate on edit mode

- CHANGELOG.md
- src/common/POLFields/DetailsFields/FieldClaimingActive.js
- src/common/POLFields/DetailsFields/FieldClaimingInterval.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.test.js
https://issues.folio.org/browse/UIOR-1192
Claiming interval should be a required field when claiming is active for PO Line.
Apply validation for claiming interval field when it's required field (claiming active).
https://github.com/folio-org/ui-orders/assets/88109087/680491f0-ba53-4b0c-bd56-705bd3051616
Ideally all of the PRs involved in breaking changes …
> UIOR-1192 Add validation for the 'claimingInterval' field

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineForm.test.js
Fixes [UIOR-1225](https://folio-org.atlassian.net/browse/UIOR-1225).
This pull request resolves an issue with the asynchronous rendering of form field elements within `<EditCustomFieldsRecord>`. Before populating the form fields with template values, it is crucial to ensure that these elements have completed rendering.
- Utilized the `onComponentLoad` prop of `<EditCustomFieldsRecord>` to ascertain if custom fields have loaded.
- Refactored `useEffect` methods to address the excessive nesting of functions, as detected by sonar.
> UIOR-1225 Wait for custom fields to render before populating form fields

- CHANGELOG.md
- translations/ui-orders/en.json
[UIOR-1118](https://folio-org.atlassian.net/browse/UIOR-1118) - Add informative error message when a user is trying to save the order template with already existing name
https://github.com/folio-org/ui-orders/assets/116072773/4da4c9f8-d60d-4f25-81a4-d0483476db43
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> UIOR-1118: handle template uniqueness error message

- CHANGELOG.md
- src/components/POLine/POLineVersionView/POLineVersionView.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POVersionView/POVersionView.js
https://folio-org.atlassian.net/browse/UIOR-1202
If the detail record displays in the third pane then the HTML Page title should display 
`<<App Title>> - <<Record title>> - FOLIO`
https://github.com/folio-org/ui-orders/assets/88109087/5aa287a1-4581-480d-bded-d7c3c3ec0606
Ideally all of the PRs involved in breaking changes would be merged in the same day …
> UIOR-1202 UX Consistency: HTML page title display when third pane (detail record) displays

- CHANGELOG.md
- package.json
- src/common/utils/locationsRestrictedFunds.js
- src/common/utils/locationsRestrictedFunds.test.js
https://folio-org.atlassian.net/browse/UIOR-1251
BE changes: https://github.com/folio-org/mod-finance/pull/244
Update form field name and normalize data.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> UIOR-1251 Apply changes in the fund schema for the locations field

- src/components/POLine/hooks/useIsFundsRestrictedByLocationIds/useIsFundsRestrictedByLocationIds.js
- src/components/POLine/hooks/useIsFundsRestrictedByLocationIds/useIsFundsRestrictedByLocationIds.test.js
https://folio-org.atlassian.net/browse/UIOR-1251
continue of #1582 
https://github.com/folio-org/ui-orders/assets/88109087/51e7df11-3fa2-4abd-b64a-fcc7d8100387
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> UIOR-1251 Align 'useIsFundRestrictedByLocationIds' with the schema changes

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIOR-1260
Transactions API was changed and requires updates on UI side as well.
https://github.com/folio-org/mod-finance/pull/245/files
> UIOR-1260 Align the 'finance.*' interfaces versions in accordance with the changes in the descriptor

- src/common/constants/constants.js
- src/settings/CentralOrdering/CentralOrdering.test.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1232
https://folio-org.atlassian.net/browse/UIOR-1232?focusedCommentId=209182
Continue of the #1581 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIOR-1232 Rename 'Empty' label for the central ordering option

- CHANGELOG.md
- package.json
- src/OrderLinesList/OrderLinesFiltersContainer.js
- src/OrderLinesList/OrderLinesFiltersContainer.test.js
https://folio-org.atlassian.net/browse/UIOR-1267
Since the locations filter is now a multi-select, it requires passing the current value of the filter (which is an array), not just one element from it.
Should be merged after:
- https://github.com/folio-org/stripes-acq-components/pull/775
- https://github.com/folio-org/ui-plugin-find-po-line/pull/159
https://github.com/folio-org/ui-orders/assets/88109087/8d4205f5-2fd2-419f-86e6-ab3cca4dd901
- Do JIRAs exist to update the impacted …
> UIOR-1267 Filter order lines by location or holding when central ordering is enabled

- CHANGELOG.md
- src/OrderLinesList/Details/OrderLineDetails.js
- src/OrderLinesList/Details/OrderLineDetails.test.js
- src/OrderLinesList/OrderLinesFiltersContainer.js
- src/OrderLinesList/OrderLinesFiltersContainer.test.js
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/Location/LocationView.js
- src/components/POLine/POLine.js
- src/components/POLine/POLine.test.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.js
- src/components/POLine/POLineVersionView/POLineVersion.js
- src/components/POLine/POLineVersionView/POLineVersionView.js
- src/components/POLine/POLineVersionView/POLineVersionView.test.js
- src/components/POLine/hooks/useSelectedPOLineVersion/useSelectedPOLineVersion.js
- src/components/POLine/hooks/useSelectedPOLineVersion/useSelectedPOLineVersion.test.js
- src/components/POLine/utils.js
- src/index.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.test.js
- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineLocationsForm/POLineLocationsForm.js
https://folio-org.atlassian.net/browse/UIOR-1233
https://folio-org.atlassian.net/browse/UIOR-1235
Update views and forms throughout the `ui-orders` module where locations are loaded to support ECS mode. In forms where `<FieldInventory>` is used, replace it with `<ConsortiumFieldInventory>`, which will add the ability to define affiliate for a specific field. 
Places to update:
- PO Line view and form
- Order template settings view and form
- PO Line version view
Adjust validation by fund-restricted locations.
https://github.com/folio-org/stripes-acq-components/assets/88109087/867467a6-2bb1-4a3c-9e68-594cd4e43815
- Does this introduce …
> UIOR-1233 ECS - Add affiliation dropdown to the PO line location form

- src/components/POLine/POLineView.js
[UIREC-299](https://folio-org.atlassian.net/browse/UIREC-299?focusedCommentId=214082) - fix the allowed number of `quantityPhysical` for creating routing lists due `NaN` type issue
> UIOR-1191: fix allowed number of `quantityPhysical` for creating routing lists #1614

- package.json
- src/components/POLine/Location/LocationView.js
- src/components/POLine/Location/LocationView.test.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineForm.test.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.test.js
- src/components/POLine/POLineVersionView/POLineVersionView.test.js
- src/components/POLine/POLineView.js
https://folio-org.atlassian.net/browse/UIOR-1235
Validation by funds' restricted locations requires checking holdings from all tenants where the instance has holdings. So in the ECS mode, we should use `consortium` search interface to get a list of consortium holdings and filter them by instance ID.
Init PR: #1609 
https://github.com/folio-org/ui-orders/assets/88109087/af33aba6-011f-45f0-b75e-78cca3c62e94
- Are the JIRAs under …
> UIOR-1235 Fetch consortium holdings by instance ID to include in validation by restricted funds

- src/settings/RoutingListConfiguration/constants.js
UIOR-1261: fix wrong routing list token for notes  [https://folio-org.atlassian.net/browse/UIREC-268?focusedCommentId=214279](https://folio-org.atlassian.net/browse/UIREC-268?focusedCommentId=214279)
> UIOR-1261: fix wrong routing list token for notes

- CHANGELOG.md
- src/components/POLine/Location/LocationView.js
- src/components/POLine/Location/LocationView.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
https://folio-org.atlassian.net/browse/UIOR-1276
Add an "Affiliation" field for the views, displaying the tenant with which the location/holding is associated.
https://github.com/folio-org/ui-orders/assets/88109087/4d3ba5ca-f3fe-4203-8c07-ee302f9d2f16 …
> UIOR-1276 ECS - Add fields indicating the affiliation of locations and holdings for views

- src/components/POLine/Location/LocationForm.js
- src/components/POLine/Location/LocationForm.test.js
- src/components/POLine/POLineForm.js
https://folio-org.atlassian.net/browse/UIOR-1235
Loading holdings when changing an instance should not completely block the form (by rendering a loading pane), but only the accordion where this data is needed.
This PR is an improvement of #1617. Change log has been already updated.
Pass `isLoading` prop to the location form and display loader on loading data.
https://github.com/folio-org/ui-orders/assets/88109087/9995e452-f927-409b-ae4b-029eb307be99
- Do JIRAs exist to update …
> UIOR-1235 UX: Display loader only for a place that requires it

- CHANGELOG.md
- src/common/hooks/useOrderLinesAbandonedHoldingsCheck/useOrderLinesAbandonedHoldingsCheck.js
- src/common/hooks/useOrderLinesAbandonedHoldingsCheck/useOrderLinesAbandonedHoldingsCheck.test.js
- src/common/utils/checkPOLinesAbandonedHoldings.js
- src/common/utils/checkRelatedHoldings.js
- src/common/utils/getConsortiumPOLineItems.js
- src/common/utils/getConsortiumPOLineItems.test.js
- src/common/utils/getConsortiumPOLineLocationTenants.js
- src/common/utils/getConsortiumPiecesAndItemsCountByHoldingIds.js
- src/common/utils/getConsortiumPiecesAndItemsCountByHoldingIds.test.js
- src/common/utils/getHoldingPiecesAndItemsCount.js
- src/common/utils/getHoldingPiecesAndItemsCount.test.js
- src/common/utils/getPOLineItems.js
- src/common/utils/getPOLinePieces.js
- src/common/utils/index.js
- src/components/PurchaseOrder/UnopenOrderConfirmationModal/UnopenOrderConfirmationModal.js
https://folio-org.atlassian.net/browse/UIOR-1291
Central ordering allows an order to have PO Lines with locations/holdings from different tenants. After opening the order, pieces and items may be created in these locations/holdings (depending on the "Receiving workflow" value). During the unopen operation, related items and pieces are deleted, and the created holdings may remain empty in different tenants. Therefore, a check for abandoned holdings in all related tenants is required.
Send requests to check for the presence of items and pieces in holdings to tenants related to the PO.
https://github.com/user-attachments/assets/87cea34e-3958-4f45-b42f-508e3dfa6ee5
- Does this PR meet or exceed the …
> UIOR-1291 ECS - Check abandoned holdings when unopen order in all dependent tenants

- CHANGELOG.md
- src/components/Utils/order/handleErrorsStrategies/index.js
- src/components/Utils/order/handleErrorsStrategies/noBudgetForFiscalYearStrategy.js
- src/components/Utils/order/handleErrorsStrategies/noExpenseClassesStrategy.js
- src/components/Utils/order/handleErrorsStrategies/restrictedLocationViolationStrategy.js
- src/components/Utils/order/showUpdateOrderError.js
- src/components/Utils/order/showUpdateOrderError.test.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1281
Display FY code in the error with the code `budgetNotFoundForFiscalYear`.
Requires: https://github.com/folio-org/stripes-acq-components/pull/817
Use the `ResponseErrorsContainer` builder to safe and useful get error details and handle them.
Apply the "Strategy" pattern for some errors for code splitting and decoupling the code.
https://github.com/user-attachments/assets/ffb96dac-ba16-4e1d-bc41-634c9978e300
- Do JIRAs exist to …
> UIOR-1281 Applied 'Strategies' approach for error handling of order updates

- CHANGELOG.md
- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
[UIOR-1323: ECS ](https://folio-org.atlassian.net/browse/UIOR-1323)- handle error message when editing POLs when user does not have all referenced affiliations
https://github.com/user-attachments/assets/5cd501d4-5207-4843-951b-319671b57ed8 …
> UIOR-1323: ECS - handle error message when editing POLs when user does not have all referenced affiliations

- CHANGELOG.md
- src/PrintOrder/PrintOrder.js
https://folio-org.atlassian.net/browse/UIOR-1339
* Fix broken 'Print order' action
* Add missing argument to `getExportData` method
> UIOR-1339 Fix print order action

- CHANGELOG.md
- package.json
* Fulfills [UIOR-1405](https://folio-org.atlassian.net/browse/UIOR-1405)
* By doing this, all permission sets can be accessed in the UI if enabled individually.
> [UIOR-1405] Add `settings.enabled` as a subpermission to all permission sets

- CHANGELOG.md
- src/common/constants/constants.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
- src/settings/CustomFieldsSettings.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
When multiple instances of the `EditCustomFieldsSettings`/ `EditCustomFieldsRecord`/ `ViewCustomFieldsRecord`/ `ViewCustomFieldsSettings` UI component, each associated with a distinct `entityType`, are used within a single application, then modifying the accordion label in one component results in an unintended change to the label in all other components. This behavior contradicts the expected functionality, causing inconsistency in the labeling of accordion sections based on entityTypes.
The issue arises due to the request sent to the configurations API to store the accordion label, which utilizes a single `configName` for all entityTypes.
Using a single `configName` for multiple entityTypes, leads to a universal change in the accordion label across all instances of the …
> UIOR-1435: Add `PO_LINE_CONFIG_NAME_PREFIX` constant and use it in the custom field components.

- CHANGELOG.md
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineView.js
- src/components/POLine/hooks/useFundsById/useFundsById.js
- src/components/POLine/hooks/useIsFundsRestrictedByLocationIds/useIsFundsRestrictedByLocationIds.js
https://folio-org.atlassian.net/browse/UIOR-1420
When opening an order, if the configuration allows PO Lines to create holdings, the corresponding instance updates the response from the `holdings-storage/holdings` or `search/consortium/holdings` endpoint by including the newly created holding.
The `useIsFundsRestrictedByLocationIds` hook relies on the data from these endpoints and skips validation for restricted locations while its internal state is `isLoading`.
However, since `react-query` caches the data, the `isLoading` flag is set to `false` after the initial fetch, meaning that on subsequent calls, the hook may proceed with outdated data while new data is still being fetched — resulting in a false error message due to the mismatch.
* Replace the check delay condition from `isLoading` …
> UIOR-1420 Display an error toast only when PO Line locations violate fund restrictions
