- package.json
updated package.json permissionSet
> Testing to master

- src/components/POLine/POLineForm.js
cost, claim, line tags, vendor, resources, physical, renewal, adjustments and license
> temporary disabled sections

- .gitignore
- src/components/POLine/POLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- src/routes/Main.js
added po line number
Fixed getDerivedStateFromProps return null
ignored stripesclirc and stripes.config.js.local
> dev to master

- package.json
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/STCOM-331
> STCOM-331 Get Pluggable from stripes-core

- src/routes/Main.js
> UIOR-7 switch to mod-orders api instead of mod-orders-storage

- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/Summary/SummaryView.js
updated /Orders page with the following fields: 
ADD into PO view details: 
Notes,
Approved,
Order type,
Re encumber
Adjustment:
credit
discount
insurance
overhead
shipment
tax_1
tax_2
use_pro_rate
DELETE from PO:
Comments
Adjustments
DELETE from PO_Line
Barcode
> UIOR-23 - Align fields for orders (view)

- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/routes/Main.js
order_format;
order_type;
payment_status;
receipt_status;
workflow_status.
> UIOR-21 add dropdown values for several fields

- src/components/POLine/POLineDetails/POLineDetailsForm.js
> UIOR-38 -Align editable PO Line Details fields

- src/components/POLine/POLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/Panes/Panes.js
- src/routes/Main.js
Now clicking on PO Line item in list of Order's PO Lines will load PO order once more to get a fresh PO line from back-end.
> UIOR-31 fix PO line details screen open

- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
> UIOR-36 Align editable Purchase Order Fields with Mockup

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/routes/Main.js
> UIOR-39 Add cost details block to PO Line

- src/components/POLine/POLineForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/POLine/Vendor/VendorView.js
- src/routes/Main.js
> UIOR-41 Add Vendor block to PO Line

- src/components/PurchaseOrder/Adjustment/AdjustmentForm.js
- src/components/PurchaseOrder/Adjustment/AdjustmentView.js
- src/components/PurchaseOrder/Adjustment/index.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
> UIOR-35 Added adjustment block in PO

- package.json
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/index.js
- src/routes/Main.js
@bonthebeerman could you please check if it's a correct way to fetch user name? With new schema PO comes with user id in `created_by` field
> UIOR-42 display name of created by user

- src/components/POLine/FundDistribution/FundDistributionView.js
- src/components/POLine/FundDistribution/index.js
- src/components/POLine/POLine.js
> UIOR-40-Add-Fund-Distribution-accordion

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
- src/components/POLine/POLine.js
Task Description
Help text for formula needs to be corrected. "List Unit Price x Quantity Ordered"
> UIOR-39 Update Cost Details block

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/CloseOrder/CloseOrderModal.js
- src/components/PurchaseOrder/PO.js
* use `FormattedDate` to display dates;
* use `format` and `normalize` on Activation Due Field to convert integer to date and vice-versa;
* fill default value from vendor's `expected_activation_interval`;
> UIOR-60 display activation due as a date

- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/routes/Main.js
> UIOR-90 fix clear assigned to field

- package.json
- src/components/POLine/Item/ItemForm.css
- src/components/POLine/Item/ItemForm.js
- translations/ui-orders/en.json
Overview: When creating an order the user may be ordering additional copies of a title they already own and have represented in inventory.
High Level Requirements:
Add new title by typing in the "Title" field
Ability to select an existing title from inventory by click the plus and using the search modal to select a title
> UIOR-66 POLine Type new Title or select a Title from inventory instances

- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
* switching back to promises on create Line, since async/await caused bug - unsaved changes modal on new Line save button;
* Eresource details view - show name of access provider instead of uuid;
* common renaming of general `initialValues` to more specific `order` or `line`.
> UIOR-59 fix line create and unsaved changes modal

- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/getOrderNumberSetting.js
- src/routes/Main.js
- src/settings/OrderNumber.js
- test/bigtest/interactors/orders.js
- translations/ui-orders/en.json
* separated function to get config from Settings response
> UIOR-78 select-suffix and prefix of order number

- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/api.js
- src/routes/Main.js
- test/bigtest/network/config.js
Reverts folio-org/ui-orders#159
> Revert "UIOR-97 change API enpoints"

- src/settings/OrderNumber.css
- src/settings/OrderNumber.js
> UIOR-96 Fix form styles

- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/api.js
- src/routes/Main.js
- test/bigtest/network/config.js
Reverts folio-org/ui-orders#161
> Revert "Revert "UIOR-97 change API enpoints""

- src/components/LayerCollection/LayerPOLine.js
- src/components/NotesForm/NotesForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.css
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
https://issues.folio.org/browse/UIOR-88
> UIOR-88 PO: Inconsistent behavior of Vendor Field

- src/components/PurchaseOrder/PO.css
- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIREC-7
> UIREC-7 Create Receive Button

- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- translations/ui-orders/en.json
Changed usage of `<button` tag to `<IconButton` component
> UIOR-81 remove hardcoded font-size

- Jenkinsfile
- src/components/LayerCollection/LayerPOLine.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/FilterConfig.js
- src/components/Utils/orderResource.js
- src/routes/Main.js
- test/bigtest/interactors/orders.js
- test/bigtest/network/factories/order.js
- test/bigtest/tests/details-order-test.js
Reverts folio-org/ui-orders#200
> Revert "UIOR-115 Update the po_number schema to use camelCase"

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/orderResource.js
- test/bigtest/network/models/order.js
The po_lines property is renamed to compositePoLines
https://issues.folio.org/browse/UIOR-112
To rename po_lines to compositePoLines
> UIOR-112 Property name change in composite_purchase_order.json schema

- src/components/Receiving/ReceivingList.js
Update receiving_history params
Change receiving_history params from 
query: 'purchase_order_id==:{id}' 
to query: 'purchaseOrderId==:{id}' …
> UIREC-8 Update Receiving_history params

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Receiving/ReceivingList.js
- src/components/Utils/api.js
- src/components/Utils/mutators.js
- src/routes/Main.js
- test/bigtest/interactors/application.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/interactors/lines-limit-modal.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/interactors/orders.js
- test/bigtest/interactors/receiving-page.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/line.js
- test/bigtest/network/models/line.js
- test/bigtest/network/models/order.js
- test/bigtest/network/serializers/line.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/edit-order-test.js
- test/bigtest/tests/orders-test.js
- test/bigtest/tests/receiving-list-test.js
UIREC-9 Add proper tests for transition to Receiving list screen
The functional code was merged to unblock Receiving List component implementation. The proper tests had required a lot of effort.
https://issues.folio.org/browse/UIREC-9
I've added a proper `line` model to Bigtest Mirage config and successfully created data in test for transition, to check that button is Appeared, clickable and transition is completed.
To achieve that I had to re-think of po lines list loading in Order Details pane.
I moved mutator of `poLine` to the Main component, so it exists in every `parentMutator` and added `accumulate: true` to appropriate resource for GET/reset functions enabled. 
- Does this PR meet or exceed …
> UIREC-9 proper unit tests

- src/components/POLine/FundDistribution/FundDistributionForm.js
- src/components/POLine/FundDistribution/FundDistributionView.js
- src/components/POLine/FundDistribution/FundId.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineForm.js
- src/components/Utils/getFundsForSelect.js
fix UIOR-124 Unable to create a po_line w/ fund_distribution, or add a fund_distribution
We need to pass `code` field for fund to save PO Line on back-end with fund distribution.
https://issues.folio.org/browse/UIOR-124 …
> UIOR-124 fix adding funds

- package.json
Fix UIOR-125 UI modules permission naming
Naming of permissions was repeating of mod-orders permissions. UI should contain its own permissions started from `ui-order.` prefix. Also we can include `orders.all` and all future permissions in mod-orders will be automatically included for UI user with edit permissions (`ui-orders.all`).
https://issues.folio.org/browse/UIOR-125
- Do PRs exist …
> UIOR-125 fix permissions for ui-orders

- translations/ui-orders/pt_BR.json
> Update translation strings as of 20190213T024543

- src/components/POLine/POLineDetails/FieldReceiptStatus.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/util.js
Some additional conditions were introduced as requirements to display Receive button on Order level.
https://issues.folio.org/browse/UIREC-10
I've separated logic in util class to reuse the same code for Order and Line level. All required info is available on UI, so we don't need to call back-en.
Ideally all of the PRs involved in breaking changes would …
> UIREC-10 Order: Receiving Button logic Update

- src/components/POLine/POLine.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/const.js
- src/index.js
- test/bigtest/interactors/line-details-page.js
- test/bigtest/tests/line-details-test.js
Apparently, it's convenient to user observe pieces of Receiving from specific PO Line, so the button Receive on PO Line Details screen was implemented.
https://issues.folio.org/browse/UIREC-12
New route to Receiving screen was added, to include URL param of PO Line. Also back-end call includes PO Line id to filter pieces on this.
Ideally all of the PRs …
> UIREC-12 Receive button on PO Line level

- src/components/POLine/Item/ItemForm.js
Some item details in PO Line form could be populated from selected title from inventory popup.
https://issues.folio.org/browse/UIOR-122 …
> UIOR-122 pull in more info then title is selected

- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/components/PurchaseOrder/renewals/RenewalsForm.js
Check-in Items checkbox looks like it is not checked when it actually has been checked on.
https://issues.folio.org/browse/UIOR-130
To add ``type="checkbox"``  for ``<Field component={Checkbox}>`` …
> UIOR-130 CheckinItems toggle not checked when coming back to edit screen

- src/routes/Main.js
The access provider dropdown list is not in alphabetical order
https://issues.folio.org/browse/UIOR-127
To sort the access provider list in alphabetical order …
> UIOR-127 PO Line Access Provider list not in alphabetical order

- src/settings/OrderNumber.js
- src/settings/OrderNumberForm.js
- test/bigtest/interactors/setting-order-number.js
- test/bigtest/tests/setting-order-number-test.js
https://issues.folio.org/browse/UIOR-119
There is a kind of regression in common component `MultiSelection`.
Also there is an improvement to save only selected values.
To provide a special `onBlur` callback, as described in appropriate readme https://github.com/folio-org/stripes-components/commit/f849b6a60384d77053918531154a3f156dd9cddd#diff-1a2907ecaea7ede31eed2b2b5066ffbe
- Do PRs …
> UIOR-119 fix Multiselection usage

- src/components/Receiving/ReceivingList.js
- test/bigtest/interactors/receiving-page.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/piece.js
- test/bigtest/network/models/piece.js
- test/bigtest/network/serializers/piece.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/receiving-list-test.js
Add tests for Receiving flow
https://issues.folio.org/browse/UIREC-19
Add model, interactors, factory, and serializer for `receiving_history`, update config.
Write tests for Receiving List, Receive and Close buttons on Receiving Page  …
> UIREC-19 Tests for Receiving flow

- translations/ui-orders/ar.json
> Update translation strings as of 20190227T140407

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190228T144944

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/Panes/Panes.js
- src/components/PurchaseOrder/PO.js
There is a bug when form component of PO Line is not refreshed on form field change. It confuses a user, since on any refresh accordions could be re-arranged.
https://issues.folio.org/browse/UIOR-128
I moved wrapper of Form component of PO Line (LayerPOLine) on the same level as View PO Line details (POLine).
Ideally all of the PRs involved in breaking …
> UIOR-128 E-resource and Physical resource accordions don't display

- src/components/Receiving/ReceivingHistory.js
Wrong property for Received date was used, it's a fix to use the proper one.
https://issues.folio.org/browse/UIREC-15 …
> UIREC-15 display right property for Received Date column

- src/components/Receiving/util.js
Fix integration with back-end for Receiving - Remove function: missed required property in request, show proper type of notification if there is at least one error on back-end happened.
https://issues.folio.org/browse/UIREC-21 …
> UIREC-21 fix integration with back-end

- src/components/Receiving/ReceivingList.js
- translations/ui-orders/en.json
User should see in Receive List PO Lines with all pieces received. There is a Receiving History tab for it.
https://issues.folio.org/browse/UIREC-16 …
> UIREC-16 do not show received lines

- src/components/Receiving/ItemDetails.css
- src/components/Receiving/ItemDetails.js
Change Modal window with Item Details (Piece Details) to support checkboxes and make it consistent with the recent mockup
https://issues.folio.org/browse/UIREC-17
Add checkboxes, logic for them, locations and item status, buttons `next` and `previous`, update Modal pane title
Ideally all of the PRs involved in breaking changes would be merged in the same …
> UIREC-17 Update order format property and style

- src/components/Receiving/ItemDetails.css
- src/components/Receiving/ItemDetails.js
- src/components/Receiving/ReceivingList.js
- translations/ui-orders/en.json
Update receiving workflow
https://issues.folio.org/browse/UIREC-17 …
> UIREC-17 Update receiving workflow

- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
Title and segmented control need to switch places and should be centered.
https://issues.folio.org/browse/UIREC-21 …
> UIREC-21 switch title and buttongroup

- translations/ui-orders/it_IT.json
> Update translation strings as of 20190313T213403

- src/components/Receiving/ItemDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/util.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
- test/bigtest/interactors/receiving-history-page.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/item.js
- test/bigtest/network/models/item.js
- test/bigtest/network/serializers/item.js
- test/bigtest/tests/receiving-history-test.js
Fetch inventory info (at first we use barcode) and show it in Piece Details modal.
https://issues.folio.org/browse/UIOR-169
On opening of Piece Details modal we construct query with item ids from pieces of selected PO lines to receive and fetch these items details. Pieces attributes extended to fetched barcodes to support editing of them and sending to the back-end for save within Receive function.
- Are the JIRAs under active …
> UIOR-169 - fetch and show barcode in Piece Details

- src/components/Receiving/ItemDetails.js
- src/components/Receiving/ReviewDetails.js
Fix `ReviewDetails` screen (show location, remove duplicates)
https://issues.folio.org/browse/UIOR-171 …
> UIOR-171 Fix ReviewDetails Screen

- src/components/POLine/Item/ItemForm.js
- src/components/Utils/Validate.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/line-edit-test.js
FOLIO should allow entering publication date (year) so long as it is a 4 digit year
https://issues.folio.org/browse/UIOR-152 …
> UIOR-152 POL publication date field does not allow future years

- src/components/Receiving/ReceivingHistory.js
After item(s) removed from history it's better to refresh the list from back-end.
https://issues.folio.org/browse/UIOR-163 …
> UIOR-163 refresh history after remove

- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReviewDetails.js
- src/components/Receiving/const.js
- src/components/Receiving/util.js
- translations/ui-orders/en.json
Item Status upon receipt/checkin: When piece is received item status should transition from "On order" to "In process".
https://issues.folio.org/browse/UIOR-182 …
> UIOR-182 Item Status upon receipt should be In process

- CHANGELOG.md
- package.json
Q1 release of ui-orders
https://issues.folio.org/browse/UIOR-153
just version increment and `orders` OKAPI bumped to 4.0 …
> UIOR-153 - Release v1.3.0

- translations/ui-orders/en_US.json
> Update translation strings as of 20190322T152325

- CHANGELOG.md
- package.json
A patch release for ui-orders with translations updated
https://issues.folio.org/browse/UIOR-153 …
> UIOR-153 - Release v1.3.1

- src/routes/Main.js
Enable sorting for columns on orders list page
https://issues.folio.org/browse/UIOR-132
Add a query builder for composite-orders manifest …
> UIOR-132 Column sorting doesn't work for order results

- translations/ui-orders/ar.json
> Update translation strings as of 20190327T174151

- src/components/Utils/order/showUpdateOrderError.js
- translations/ui-orders/en.json
Update message per description
https://issues.folio.org/browse/UIOR-146
While it's …
> UIOR-146 update error message

- src/components/CheckIn/CheckIn.js
- src/components/CheckIn/CheckInDetails.js
- src/components/CheckIn/CheckInHistory.js
- src/components/CheckIn/CheckInHistoryWrapper.js
- src/components/CheckIn/CheckInItems.js
- src/components/CheckIn/CheckInItemsWrapper.js
- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/PiecesList.js
- src/components/CheckIn/withCheckboxes.js
- src/components/Receiving/util.js
- test/bigtest/interactors/check-in-history-page.js
- test/bigtest/tests/check-in-history-test.js
- translations/ui-orders/en.json
Users need to be able to remove Checkin items that have been checked in when the notice they have made a mistake.
https://issues.folio.org/browse/UIOR-159
Tab of Check-in history was implemented, as well as remove from history function for checked items only (confirmation modal included). …
> UIOR-159 Access Checkin History and Remove Items

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Physical/PhysicalForm.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/line-create-test.js
the list of organization will continue to grow and users will need the ability to filter and select a Vendor. The Vendor lockup would be overkill here.
Another component has been used to select vendors + added initial values …
> UIOR-189 Update vendor dropdown in E and Physical resource accordions in PO Line

- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/util.js
- src/components/POLine/Eresources/MaterialTypeField.js
- src/components/POLine/Other/OtherForm.js
- src/components/Utils/const.js
On UI we need to fix Location select on CheckIn Details modal - location is an optional field and it could not be filled on the piece.
https://issues.folio.org/browse/UIOR-195
Add empty value in `Location` dropdown option  …
> UIOR-195 Certain locations prevent check-in

- src/components/CheckIn/AddPieceModal.js
- src/components/CheckIn/CheckInDetails.js
- src/components/CheckIn/CheckInItems.js
- src/components/CheckIn/CheckInItemsWrapper.js
- src/components/CheckIn/util.js
- test/bigtest/interactors/add-piece-modal.js
- test/bigtest/network/config.js
- test/bigtest/tests/check-in-items-test.js
Users need to be able to Checkin items from `AddPieceModal`
The button Check-in is there already and we need to call the same function as from list, except it should be called after piece is created.
https://issues.folio.org/browse/UIOR-194 …
> UIOR-194 Check-in button in Add Piece modal

- src/components/POLine/POLineForm.js
When duplicating PO unable to add POL without closing POL create and clicking Add POL
https://issues.folio.org/browse/UIOR-199
Add to POLineForm property `enableReinitialize: true`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> UIOR-199 When duplicating PO unable to add POL

- src/components/Receiving/ReceivingHistory.js
Purpose: Improve performance when PO has a lot of items in receiving history.
https://issues.folio.org/browse/UIOR-175
Change component configuration and fetch data query …
> UIOR-175 Infinite scroll in receiving history

- src/common/constants/index.js
- src/common/constants/poStatuses.js
- src/components/POLine/POLineDetails/FieldPaymentStatus.js
- src/components/POLine/POLineDetails/FieldReceiptStatus.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
it need to provide only available options for dropdowns
https://issues.folio.org/browse/UIOR-147
created maps return available options lists depends on PO workflow status …
> UIOR-147 Align POL Payment and Receipt status with PO Status

- src/components/CheckIn/AddPieceModal.js
- src/components/CheckIn/CheckIn.js
- src/components/CheckIn/CheckInDetails.js
- src/components/CheckIn/CheckInItems.js
- src/components/CheckIn/CheckInItemsWrapper.js
- src/components/CheckIn/CheckInNavigation.js
- src/components/CheckIn/FieldPieceFormat.js
- src/components/CheckIn/const.js
- test/bigtest/interactors/add-piece-modal.js
- test/bigtest/tests/check-in-items-test.js
Right now on Add Piece modal in Check-in we have Location dropdown, it should be required only if PO Line appropriate block (physical or electronic details, according to piece format) has option Instance, Holding, Item or Instance, Holding of Create Inventory.
Add Item button should be disabled in the case that Item Creation is NOT required.
https://issues.folio.org/browse/UIOR-203
- Do …
> UIOR-203 Checkin:Add Pieces - required fields

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190415T231934

- package.json
- src/components/CheckIn/AddPieceModal.js
- src/components/CheckIn/CheckInItems.js
- test/bigtest/interactors/add-piece-modal.js
- test/bigtest/tests/check-in-items-test.js
- translations/ui-orders/en.json
Usage of ui-plugin-create-item on Add Item button
https://issues.folio.org/browse/UIOR-167
Basically, the same as other stripes plugins - `Pluggable` component is included on the page and required props provided to it. …
> UIOR-167 Call ui-plugin-get-item

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/FieldCurrency.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/POLine/Vendor/VendorView.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/line-create-test.js
- test/bigtest/tests/line-edit-test.js
- test/bigtest/tests/line-number-test.js
- translations/ui-orders/en.json
It needs  some fields to be populated from vendor to POL
https://issues.folio.org/browse/UIOR-184
set initial values for POL fields based on vendor, 
Added functionality to create select lists based on vendor properties …
> UIOR-184 Add data to POL based on vendor

- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReviewDetails.js
- src/components/Receiving/util.js
- test/bigtest/interactors/piece-details-modal.js
- test/bigtest/tests/piece-details-test.js
- translations/ui-orders/en.json
it needs to be able to add comment for receiving piece
https://issues.folio.org/browse/UIOR-207
added input field for adding comment in receive pieces modal
updated model for saving
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> UIOR-207 allow user to add comment to Piece when receiving

- src/components/CheckIn/CheckInDetails.js
Fix default Item status from `Received` to `In Process`
https://issues.folio.org/browse/UIOR-197 …
> UIOR-197 Check-in Item status in Process

- src/components/POLine/Item/ItemForm.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineForm.js
it needs to move POL item details on top
https://issues.folio.org/browse/UIOR-213
reordered accordions in form and view …
> UIOR-213 move item details accordion to top of view

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190501T184815

- translations/ui-orders/ar.json
> Update translation strings as of 20190502T124851

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190503T205536

- src/components/CheckIn/AddPieceModal.js
- src/components/CheckIn/CheckInDetails.js
- src/components/CheckIn/CheckInItemsWrapper.js
Some review fixes
* when checking in the resulting item status is all lower case (Different from receiving and different from what is written in check-in modal for item status)
* when electronic resource has "create item"=Instance, holding I can still add item record from Piece creation modal;
* it seems that when immediately checking in a piece after creating an Item associated with it. The item status is set to "Received". It should also be set to "In process";
https://issues.folio.org/browse/UIOR-167
- What other modules …
> UIOR-167 fix story review issues

- package.json
- src/common/RepeatableFieldWithErrorMessage/RepeatableFieldWithErrorMessage.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POForm.js
- src/components/SelectItemStatus/SelectItemStatus.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/network/boot.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/edit-order-test.js
move "Owner" field to PO level
* minor fix of warning on `data-test-poLineEstimatedPrice` html attribute;
* bump stripes version to not import `stripes-core` separately;
https://issues.folio.org/browse/UIOR-227 …
> UIOR-227 Move owner to order level

- .editorconfig
- package.json
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/routes/Main.js
- test/bigtest/tests/create-order-test.js
- test/bigtest/tests/line-create-test.js
* display owner column;
* added .editorconfig;
* default sort by poNumber (https://issues.folio.org/browse/UIOR-214);
https://issues.folio.org/browse/UIOR-220 …
> UIOR-220 display owner column

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190517T183537

- src/OrdersList/OrdersListFilters.js
Include endDate in filtering
https://issues.folio.org/browse/UIOR-206 …
> UIOR-206 include endDate

- src/components/CheckIn/PiecesList.js
customer wants to see piece format in Check-in flow
https://issues.folio.org/browse/UIOR-212
added appropriated column for check-in pieceList
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIOR-212 Display "Piece format" in Check-in area and wizard table

- package.json
- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/index.js
- src/OrdersList/OrdersList.js
- src/common/OrdersNavigation/OrdersNavigation.js
- src/common/OrdersNavigation/index.js
- src/common/constants/api.js
- src/common/constants/index.js
- src/common/constants/routes.js
- src/index.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/tests/order-lines-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-27
Users need the ability to search and filter orders and order lines by a number of different field values. This will help them find exactly what they are looking for and what they should be working with.
new route with Order lines
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> UIOR-27 Reorganize the search and filter pane on the Orders landing page

- src/OrderLinesList/OrderLinesList.js
- translations/ui-orders/en.json
config for SearchAndSort columns
While it's …
> UIOR-270 Revise the Order Lines search results list columns - add columns

- src/OrderLinesList/OrderLinesList.js
add column-cql mapping to the resource
While …
> UIOR-270 Revise the Order Lines search results list columns - sorting

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190523T143922

- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/constants.js
- src/OrdersList/OrdersList.js
- src/common/utils/getLocationOptions.js
- src/common/utils/index.js
- src/components/Utils/resources.js
- translations/ui-orders/en.json
Initial resources and Order Lines list changes
https://issues.folio.org/browse/UIOR-267 …
> UIOR-267 resources config

- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-223
Change error message …
> UIOR-223 Add appropriate error message

- package.json
- src/OrderLinesList/Details/Details.js
- src/OrderLinesList/Details/OrderLineDetails.js
- src/OrderLinesList/Details/index.js
- src/OrderLinesList/OrderLinesList.js
- src/components/POLine/FundDistribution/FundDistributionView.js
- src/components/POLine/FundDistribution/FundId.js
- src/components/POLine/Location/LocationView.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
- src/components/POLine/index.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
- src/index.js
- test/bigtest/tests/OrderLinesList/line-details-test.js
- test/bigtest/tests/OrderLinesList/order-lines-test.js
- test/bigtest/tests/line-details-test.js
Overview: When search results display for POL searches and filters, this story describes what columns and data should appear
move POL view to common component and reuse it in 2 places …
> UIOR-270 PO line details on order lines list screen

- src/OrdersList/OrdersList.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/util.js
- src/components/Utils/api.js
- src/components/Utils/const.js
- src/components/Utils/orderResource.js
- src/components/Utils/resources.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/network/config.js
- test/bigtest/tests/details-order-test.js
- translations/ui-orders/en.json
Enhance Bill To and Ship addresses
https://issues.folio.org/browse/UIOR-91
Populate the bill to and ship to select lists with the library addresses from "Tenant" addresses in settings
Bill to and ship to address display in the view …
> UIOR-91 Enhance Bill To and Ship addresses

- src/components/PurchaseOrder/LinesLimit/LinesLimit.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/resources.js
- src/settings/ClosingReasons/ClosingReasonItem.js
- src/settings/ClosingReasons/ClosingReasonsContainer.js
- test/bigtest/interactors/lines-limit-modal.js
- test/bigtest/tests/check-in-items-test.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/line-details-test.js
- test/bigtest/tests/line-edit-test.js
- test/bigtest/tests/line-number-test.js
- test/bigtest/tests/receiving-list-test.js
- translations/ui-orders/en.json
Some translations were missed. Also closing reasons resource clean-up
https://issues.folio.org/browse/UIOR-201 …
> UIOR-201 localize strings, resource clean-up

- src/components/POLine/POLineDetails/FieldPaymentStatus.js
- src/components/POLine/POLineDetails/FieldReceiptStatus.js
- test/bigtest/tests/add-line-test.js
- test/bigtest/tests/details-order-test.js
test is failing, but maybe leveraging it to a separate file might resolve an issue (reduce nesting in mocha describes) …
> fix tests (leverage failing one)

- src/components/POLine/POLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/PO.js
- test/bigtest/interactors/line-details-page.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/line-details-test.js
- test/bigtest/tests/order-details-with-line-test.js
We shouldn't reset filters or search by clicking on PO Line row in Order Details. The same when we go back to PO from PO Line Details Pane.
I've used the way suggested in stripes https://github.com/folio-org/stripes/blob/master/doc/dev-guide.md#url-navigation
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> Fix reset of sorting and filters on PO Line details

- src/components/POLine/Item/util.js
Fix instanceId value from `''` to `null` …
> UIOR-228 Fix instanceId value

- src/OrderLinesList/OrderLinesList.js
> UIOR-270 fix productId and fund code displaying on order lines screen

- src/OrderLinesList/OrdersLinesSearchConfig.js
- translations/ui-orders/en.json
Add search by product Id ([UIOR-263](https://issues.folio.org/browse/UIOR-263?focusedCommentId=52502&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-52502))
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> UIOR-263 Add search by product Id

- src/OrderLinesList/OrderLinesFilters.js
* Only Partially received is checked; please include Pending and Awaiting receipt as well
* Only Partially paid is checked; please include Pending and Awaiting payment as well
https://issues.folio.org/browse/UIOR-267 …
> UIOR-267 more default filter options

- package.json
- src/OrderLinesList/OrderLinesList.js
- src/common/OrdersNavigation/OrdersNavigation.js
set default sort, use funds to get codes
While …
> UIOR-270 fix some issues

- src/OrderLinesList/Details/OrderLineDetails.js
object_object request
use accumulate resource …
> UIOR-270 fix order loading

- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListSearchConfig.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-261
set up search config …
> UIOR-261 Create the primary search options for Orders

- package.json
https://issues.folio.org/browse/UIOR-256
Purpose: Deleting a PO should have a separate permission from creating or updating a PO, so that it can be assigned to a narrower group of staff than standard PO CRUD permissions
add new set of ui permissions …
> UIOR-256 Separate permission for deleting PO from view, create and edit PO perms

- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
https://issues.folio.org/browse/UIOR-292
new property from SearchAndSort is used
https://github.com/folio-org/stripes-smart-components/pull/538
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIOR-292 Suppress up/down arrow for search results columns that cannot be sorted

- src/components/PurchaseOrder/PODetails/PODetailsForm.css
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.css
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/PODetails/css/PODetailsView.css
Make the acquisitions addresses retain line breaks
https://issues.folio.org/browse/UIOR-296
add property `white-space: pre-line` to address block …
> UIOR-296 Make the acq addresses retain line breaks

- src/OrderLinesList/Details/OrderLineDetails.js
- src/OrderLinesList/OrderLinesList.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemView.js
- src/components/POLine/Item/ProductIdDetails.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
- src/components/Utils/getIdentifierTypesForSelect.js
PO Line: product id type is uuid
https://issues.folio.org/browse/UIOR-288
UI needs to be updated to provide uuid instead of name when communicating with the backend
Could be merged only after [MODORDERS-252](https://issues.folio.org/browse/MODORDERS-252)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> UIOR-288-PO Line: product id type is uuid

- src/OrdersList/OrdersList.js
Orders list has narrow columns and huge unused space for the last columns. With explicitly set of column widths it looks better …
> fix list width, it has narrow columns

- src/OrdersList/OrdersListSearchConfig.js
https://issues.folio.org/browse/UIOR-261
update keyword search index config
While it's …
> UIOR-261 update Orders keyword search

- src/components/CheckIn/CheckInItems.js
- src/components/CheckIn/CheckInItemsActions.js
Fix edit of piece, since request of PUT piece is different from GET of Receiving history API.
https://issues.folio.org/browse/UIOR-252 …
> UIOR-252 fix of edit piece (PUT)

- translations/ui-orders/pt_BR.json
> Update translation strings as of 20190611T141613

- package.json
Update `orders` version to 6.0 …
> Update orders and org-storage versions

- CHANGELOG.md
- package.json
`ui-orders` release
https://issues.folio.org/browse/UIOR-293 …
> Release v1.5.0

- package.json
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
https://issues.folio.org/browse/UIOR-256
https://issues.folio.org/browse/UIOR-259
new set of permissions …
> UIOR-256 Separate permission for PO, POL, receiving and check-in

- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
To reduce the number of clicks to open accordions when creating/updating/viewing order lines
https://issues.folio.org/browse/UIOR-280
Opened all accordions on POL screens …
> UIOR-280 expand all accordions

- src/OrderLinesList/OrderLinesList.js
https://issues.folio.org/browse/UIOR-298
use new property from https://github.com/folio-org/stripes-smart-components/pull/548 …
> UIOR-298 Fix order line search results header

- src/components/POLine/Item/ItemView.js
To easily navigate between the POL and its related instance
https://issues.folio.org/browse/UIOR-286
Switched title to link if POL have instanceId …
> UIOR-286 show link if have instanceId

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/FieldCurrency.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Eresources/MaterialTypeField.js
- src/components/POLine/FundDistribution/FundDistributionForm.js
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineDetails/FieldAcquisitionMethod.js
- src/components/POLine/POLineDetails/FieldOrderFormat.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/POLine/Physical/VolumesForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/PurchaseOrder/PODetails/FieldOrderType.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/components/PurchaseOrder/renewals/RenewalsForm.js
- src/components/PurchaseOrder/util.js
- src/settings/InventoryRecordTypeSelectField.js
https://issues.folio.org/browse/UIOR-294
Problem: Do not want to have to close orders to update minor information that will not necessarily concern the vendor but be important for reporting.
set disabled property for set of fields …
> UIOR-294 Allow select PO and POL fields to be edited when order is open

- package.json
https://issues.folio.org/browse/UIOR-256
new permission …
> UIOR-256 separate permissions remove lines

- src/components/Receiving/ReceivingList.js
- test/bigtest/tests/piece-details-test.js
When receiving a single-line PO, have the line automatically selected when the user presses the receive button
https://issues.folio.org/browse/UIOR-245
Set checked PO automatically if have only one PO   …
> UIOR-245 check line if for receive have only one item

- src/components/Receiving/LineDetails.js
Comment should be enabled to edit. It's a copy-paste error …
> Enable comment editing without conditions

- src/OrderLinesList/OrderLinesList.js
https://issues.folio.org/browse/UINV-24
reuse some methods in plugin repo
add methods to prototype …
> UINV-24 Search and select POL plugin

- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/TemplateInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/index.js
- src/settings/OrderTemplates/constants.js
- translations/ui-orders/en.json
add constants and translations for order templates accordions …
> UIOR-237 accordions set up for order templates

- src/components/POLine/POLineView.js
- src/components/POLine/const.js
- test/bigtest/interactors/check-in-history-page.js
- test/bigtest/interactors/orders.js
- test/bigtest/interactors/receiving-history-page.js
- test/bigtest/interactors/receiving-page.js
- test/bigtest/interactors/settings/ClosingReasons/ClosingReasons.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesEditor.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesList.js
- test/bigtest/interactors/settings/settings.js
- test/bigtest/tests/PurchaseOrder/close-order-modal-test.js
- test/bigtest/tests/add-line-test.js
- test/bigtest/tests/check-in-history-test.js
- test/bigtest/tests/checkIn-details-modal-test.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/line-details-test.js
- test/bigtest/tests/order-details-with-line-test.js
- test/bigtest/tests/orders-test.js
- test/bigtest/tests/piece-details-test.js
- test/bigtest/tests/receiving-history-test.js
- test/bigtest/tests/receiving-list-test.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-editor-test.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-list-test.js
- test/bigtest/tests/settings/closing-reasons-test.js
- test/bigtest/tests/settings/settings-test.js
- translations/ui-orders/en.json
Button collapse all is lower. Also Accrodion for PO Line details is introduced.
While …
> fix collapse all button position

- src/OrdersList/OrdersListFilters.js
- src/OrdersList/constants.js
Make more informative field Renewal manual
https://issues.folio.org/browse/UIOR-306 …
> UIOR-306 change filter options for Renewal manual

- src/common/FieldSelection/FieldSelection.js
- src/common/FieldSelection/index.js
- src/common/POFields/FieldBillTo.js
- src/common/POFields/FieldIsManualPO.js
- src/common/POFields/FieldIsReEncumber.js
- src/common/POFields/FieldPrefix.js
- src/common/POFields/FieldShipTo.js
- src/common/POFields/FieldSuffix.js
- src/common/POFields/FieldVendor.js
- src/common/POFields/index.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/Utils/const.js
- src/components/Utils/resources.js
- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformation/PurchaseOrderInformation.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformation/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/index.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesEditor.js
- translations/ui-orders/en.json
add form submit action + reuse of PO fields …
>  UIOR-237 create order templates - save action with initial fields

- src/common/POFields/FieldsNotes/FieldsNotes.js
- src/common/POFields/FieldsNotes/index.js
- src/common/POFields/index.js
- src/components/NotesForm/NotesForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformation/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderNotesForm/PurchaseOrderNotesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderNotesForm/index.js
move note fields to common and use it
While …
>  UIOR-237 create order templates - PO notes

- src/common/POFields/FieldIsApproved.js
- src/common/POFields/index.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderSummaryForm/PurchaseOrderSummaryForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderSummaryForm/index.js
move fields to common and use it
While it's …
>  UIOR-237 create order templates - PO summary

- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/common/POLFields/FieldsLocation/index.js
- src/common/POLFields/FieldsLocation/validate.js
- src/common/POLFields/index.js
- src/components/POLine/Location/LocationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineLocationsForm/POLineLocationsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineLocationsForm/index.js
move field to common and reuse it
While it's …
>  UIOR-237 create order templates - POL locations

- src/common/POLFields/FieldsFundDistribution/FieldsFundDistribution.js
- src/common/POLFields/FieldsFundDistribution/index.js
- src/common/POLFields/index.js
- src/components/POLine/FundDistribution/FundDistributionForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineFundDistributionForm/POLineFundDistributionForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineFundDistributionForm/index.js
>  UIOR-237 create order templates - POL fund distribution

- src/common/POLFields/VendorFields/FieldRefNumberType.js
- src/common/POLFields/VendorFields/FieldVendorAccountNumber.js
- src/common/POLFields/VendorFields/FieldVendorInstructions.js
- src/common/POLFields/VendorFields/FieldVendorNote.js
- src/common/POLFields/VendorFields/FieldVendorRefNumber.js
- src/common/POLFields/index.js
- src/components/POLine/Vendor/VendorForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/POLineVendorForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/index.js
fields unification and re-usage 
While it's …
> UIOR-237 Create order templates in settings - POL vendor

- src/components/POLine/Cost/CostView.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/FundDistribution/FundDistributionView.js
- src/components/POLine/Item/ItemView.js
- src/components/POLine/Item/ProductIdDetails.js
- src/components/POLine/Location/LocationView.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineView.js
- src/components/POLine/Physical/PhysicalView.js
- src/components/POLine/Vendor/VendorView.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplateView/TemplateInformationView/TemplateInformationView.js
- src/settings/OrderTemplates/OrderTemplateView/TemplateInformationView/index.js
- src/settings/OrderTemplates/OrderTemplateView/index.js
- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.js
- src/settings/OrderTemplates/util.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplateView.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesEditor.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesList.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-list-test.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-view-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-238
add base structure for View, Edit and delete "Order templates" …
> UIOR-238 View, Edit and delete "Order templates"

- src/common/utils/getAddressOptions.js
- src/common/utils/getAddresses.js
- src/common/utils/getSettingsList.js
- src/common/utils/index.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/util.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- src/settings/Prefixes.js
- src/settings/Suffixes.js
add BE resources and utils reusage
While it's …
>  UIOR-237 create order templates - PO info values

- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
- src/common/POLFields/EresourcesFields/FieldActivated.js
- src/common/POLFields/EresourcesFields/FieldActivationDue.js
- src/common/POLFields/EresourcesFields/FieldExpectedActivation.js
- src/common/POLFields/EresourcesFields/FieldTrial.js
- src/common/POLFields/EresourcesFields/FieldUserLimit.js
- src/common/POLFields/FieldMaterialType.js
- src/common/POLFields/index.js
- src/components/POLine/Eresources/EresourcesForm.css
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/index.js
> UIOR-237 Create order templates - eresources form

- src/components/POLine/Item/InstancePlugin.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
> UIOR-237 create order templates - item details

- src/common/POLFields/PhysicalFields/FieldExpectedReceiptDate.js
- src/common/POLFields/PhysicalFields/FieldMaterialSupplier.js
- src/common/POLFields/PhysicalFields/FieldReceiptDue.js
- src/common/POLFields/PhysicalFields/FieldsVolume.js
- src/common/POLFields/index.js
- src/components/POLine/Physical/PhysicalForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/POLinePhysicalForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/index.js
> UIOR-237 create order templates - physical resources form

- src/components/POLine/Cost/FieldCurrency.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
> UIOR-237 create order templates - cost details

- src/components/Utils/orderResource.js
- src/components/Utils/resources.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.js
- src/settings/OrderTemplates/constants.js
- test/bigtest/network/config.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-list-test.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-view-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-238
add `orderTemplate` resource for edit and method PUT
add conditional rendering for View accordions …
> UIOR-238 Add orderTemplate resource, conditional rendering

- src/common/POFields/FieldAssignedTo/FieldAssignedTo.css
- src/common/POFields/FieldAssignedTo/FieldAssignedTo.js
- src/common/POFields/FieldAssignedTo/index.js
- src/common/POFields/FieldPrefix.js
- src/common/POFields/FieldSuffix.js
- src/common/POFields/RenewalFields/FieldIsManualRenewal.js
- src/common/POFields/RenewalFields/FieldRenewalDate.js
- src/common/POFields/RenewalFields/FieldRenewalInterval.js
- src/common/POFields/RenewalFields/FieldRenewalPeriod.js
- src/common/POFields/index.js
- src/common/POFields/utils.js
- src/common/POLFields/index.js
- src/common/POLFields/utils.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.css
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/renewals/RenewalsForm.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/POLineOtherResourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderRenewalsForm/PurchaseOrderRenewalsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderRenewalsForm/index.js
- src/settings/OrderTemplates/constants.js
- translations/ui-orders/en.json
> UIOR-237 create order tempaltes

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190627T152539

- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
https://issues.folio.org/browse/UIOR-238
Add `vendorName` and `assignedTo` to template View screen  …
> UIOR-238 Add VendorName and assignedTo to View

- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/renewals/RenewalsView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
https://issues.folio.org/browse/UIOR-238
Fix conditional rendering for Renewals accordion …
> UIOR-238 Fix orderType isOngoing

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190628T192643

- src/OrdersList/OrdersList.js
- src/components/FolioFormattedDate/FolioFormattedDate.js
- src/components/FolioFormattedDate/index.js
- src/components/POLine/Other/OtherView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- test/bigtest/network/factories/line.js
- test/bigtest/network/factories/order.js
Last updated [date only, no time]
https://issues.folio.org/browse/UIOR-269
New common component is created to handle case when value is not defined …
> UIOR-269 show date in last updated column

- src/common/POFields/FieldVendor.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/UIOR-277
disabled property …
> UIOR-277 fix vendor field disabling

- src/components/Receiving/ReceivingList.js
https://issues.folio.org/browse/UIOR-315
pass receivings insead of line group for toggle  …
> UIOR-315 Not all pieces are displayed in receiving wizard

- src/OrderLinesList/OrderLinesFilters.js
Fix `Actual Receipt Date` and `Expected Activation Date` filters
https://issues.folio.org/browse/UIOR-268 …
> UIOR-268 Fix Actual Receipt Date and Expected Activation Date filters

- src/OrdersList/OrdersList.js
- src/common/OrdersNavigation/OrdersNavigation.js
- test/bigtest/tests/PurchaseOrder/open-order-confirmation-modal-test.js
Default sorting should be descending on po numbers
https://issues.folio.org/browse/UIOR-269 …
> UIOR-269 fix sorting descending

- src/common/constants/defaultCloseOrderReasons.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-266
Add `Complete` to the list of to default reasons for closure …
> UIOR-266 Add 'Complete' to default reasons for closure

- src/components/Receiving/ItemDetails.js
- src/components/Receiving/LineDetails.js
When adding a barcode to a piece during receiving, automatically select that piece for receipt.
https://issues.folio.org/browse/UIOR-246
Select a piece if the barcode has been changed.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> UIOR-246 automatically select the piece

- src/common/ClosingReasonFilter/ClosingReasonFilter.js
- src/common/constants/defaultCloseOrderReasons.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-266
Fix filter for Reason for closure
While it's …
> UIOR-266 Fix filter for Reason for closure

- src/OrdersList/OrdersListSearchConfig.js
https://issues.folio.org/browse/UIOR-262
Fix the secondary search options for Orders …
> UIOR-262 Fix the secondary search options for Orders

- package.json
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/PurchaseOrder/renewals/RenewalsView.js
- test/bigtest/helpers/prefixKeys.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/line-details-page.js
- test/bigtest/tests/PurchaseOrder/open-order-confirmation-modal-test.js
- test/bigtest/tests/PurchaseOrder/update-order-error-modal-test.js
- translations/ui-orders/en.json
bump interface versions.
https://issues.folio.org/browse/UIOR-322 …
> UIOR-322 bump interface of inventory

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190709T154346

- src/common/POLFields/FieldsFundDistribution/FieldsFundDistribution.js
- src/common/POLFields/FieldsLocation/FieldsLocation.js
Fix all RepeatableField component places to support the new layout
https://issues.folio.org/browse/UIOR-309 …
> UIOR-309 Fix RepeatableField component

- translations/ui-orders/ar.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
> Update translation strings as of 20190711T172340

- package.json
- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/check-in-history-test.js
- test/bigtest/tests/check-in-items-test.js
- test/bigtest/tests/create-order-test.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/order-open-test.js
Bigtest suite is failing a lot without any visible reason. …
> leverage test, increase some timeouts, join several `it`s

- src/OrdersList/OrdersList.js
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/getOrderTemplateValue.js
- src/components/Utils/getOrderTemplatesForSelect.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/interactors/orders.js
- test/bigtest/tests/create-order-test.js
- test/bigtest/tests/edit-order-test.js
- test/bigtest/tests/line-create-test.js
- test/bigtest/tests/line-edit-test.js
To enhance the order process and improve workflows
https://issues.folio.org/browse/UIOR-301
Add opportunity to chose template for new orders.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIOR-301 Create PO and POL(s) using order templates

- src/common/POFields/FieldIsApproved.js
- src/common/POFields/FieldIsManualPO.js
- src/common/POFields/FieldIsReEncumber.js
- src/common/POFields/RenewalFields/FieldIsManualRenewal.js
- src/common/POLFields/DetailsFields/FieldCancellationRestriction.js
- src/common/POLFields/DetailsFields/FieldCheckInItems.js
- src/common/POLFields/DetailsFields/FieldCollection.js
- src/common/POLFields/DetailsFields/FieldRush.js
- src/common/POLFields/EresourcesFields/FieldActivated.js
- src/common/POLFields/EresourcesFields/FieldTrial.js
- src/components/CheckIn/AddPieceModal.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
For form input suits more vertical layout of checkboxes …
> fix checkboxes layout

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/Utils/const.js
Should be merged together with https://github.com/folio-org/acq-models/pull/163
* poLine.source is an enum, so display proper label at details and edit screens.
* set source field as `User` by default.
https://issues.folio.org/browse/UIOR-318 …
> UIOR-318 set Source as User

- src/OrderLinesList/OrdersLinesFilterConfig.js
To fix filter by source (because it's an enum now)
https://issues.folio.org/browse/UIOR-318 …
> UIOR-318 fix filter by Source

- package.json
https://issues.folio.org/browse/UIOR-324 …
> UIOR-324 update interfaces

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-301
Fixed contributor name type list on PO template …
> UIOR-301 fix contributor type list on po template

- src/common/POFields/FieldVendor.js
- src/common/POFields/RenewalFields/FieldRenewalDate.js
- src/common/POFields/RenewalFields/FieldRenewalInterval.js
- src/common/POLFields/DetailsFields/FieldAcquisitionMethod.js
- src/common/POLFields/DetailsFields/FieldOrderFormat.js
- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
- src/common/POLFields/FieldMaterialType.js
- src/common/POLFields/FieldsFundDistribution/FieldsFundDistribution.js
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/FieldCurrency.js
- src/components/POLine/FundDistribution/FundDistributionView.js
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Location/LocationView.js
- src/components/PurchaseOrder/PODetails/FieldOrderType.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineFundDistributionForm/POLineFundDistributionForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/POLineOtherResourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/POLinePhysicalForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderRenewalsForm/PurchaseOrderRenewalsForm.js
https://issues.folio.org/browse/UIOR-311
not validate if not required …
> UIOR-311 Remove required fields from PO templates

- src/common/POLFields/FieldMaterialType.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/PurchaseOrder/util.js
- src/components/Utils/Validate.js
https://issues.folio.org/browse/UIOR-328
Added behavior for required …
> Uior 328 material type should have asterisk if required

- src/components/POLine/POLineInvoices/POLineInvoices.js
- src/components/PurchaseOrder/POInvoices/POInvoices.js
https://issues.folio.org/browse/UIOR-123
fix link to invoice …
> UIOR-123 fix link

- package.json
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/UIOR-300
use common component from stripes-acq
While …
> UIOR-300 Ability to assign acquisition unit(s) to order records

- package.json
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/UIOR-300
permissions and props …
> UIOR-300 assign units permission

- package.json
https://issues.folio.org/browse/UIOR-300
change name …
> UIOR-300 fix manage acq units permission name

- package.json
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/UIAC-4
perm names …
> UIAC-4 Change acquisition unit(s) assignment for orders

- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListFilterConfig.js
- src/OrdersList/OrdersListFilters.js
- src/OrdersList/constants.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
Add ability to filter Orders by Acquisitions unit
https://issues.folio.org/browse/UIOR-316 …
> UIOR-316 re-use Acq unit filter

- src/components/PurchaseOrder/PODetails/PODetailsView.js
https://issues.folio.org/browse/UIAC-8
AcqUnitsView component usage …
> UIAC-8 View acquisition unit(s) assignment for individual record (order)

- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/PO.js
Funds are not displayed in PO Lines list at PO Details pane. …
> fix fund codes

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190815T130307

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190819T080537

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190903T134424

- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- src/components/CheckIn/CheckIn.js
- src/components/POLine/Item/InstancePlugin.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/index.js
- src/settings/OrdersSettings.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplateView.js
- test/bigtest/tests/receiving-history-test.js
Fixed also react-router usage in index.js, to refresh lists properly.
https://issues.folio.org/browse/UIOR-345 …
> UIOR-345 fix find-instance, fix list refreshes

- src/components/PurchaseOrder/PODetails/PODetailsForm.css
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.css
Long address lines should wrap and not crash into the next field.
https://issues.folio.org/browse/UIOR-362 …
> UIOR362 BillTo/ShipTo address not aligned properly

- src/components/Utils/getOrderTemplatesForSelect.js
- src/settings/OrderTemplates/util.js
- test/bigtest/tests/create-order-test.js
The list of templates should be in alphabetical order in Settings and in the Create order screen
https://issues.folio.org/browse/UIOR-364 …
> UIOR-364 Order templates not in alphabetical order

- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrdersLinesSearchConfig.js
- src/OrdersList/OrdersListSearchConfig.js
To fix search query with `Keyword` option.
https://issues.folio.org/browse/UIOR-367
The search query is failing due to incorrect format of `queryTemplate`. So to fix this we use a common function to generate queryTemplate. …
> UIOR-367 fix search query

- src/common/POLFields/VendorFields/FieldRefNumberType.js
- src/common/utils/getAddressOptions.js
- src/common/utils/getClosingReasonsOptions.js
- src/components/PurchaseOrder/CloseOrder/CloseOrderModal.js
- src/components/Utils/resources.js
Set options for select `locations`, `users`, `closing reasons`, `material types`, `identifiers types`, `contributor name types` in alphabetic order
https://issues.folio.org/browse/UIOR-356
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> UIOR-356 Options for select in alphabetic order

- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
POL Column headers and results not aligned in 3 pane display
https://issues.folio.org/browse/UIOR-363
Remove prop `ColumnWidths` …
> UIOR-363 Columns not aligned in 3 pane display

- src/components/POLine/Item/ItemForm.js
To only add the product identifiers from the Instance to the POL, and to exclude the record identifiers, based on the Resource identifier types.
https://issues.folio.org/browse/UIOR-373
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> UIOR-373 Reduce the Resource identifier types

- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/PiecesList.js
- src/components/POLine/POLineInvoices/POLineInvoices.js
- src/components/PurchaseOrder/POInvoices/POInvoices.js
- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/ReviewDetails.js
ACQ Apps: MCL column width updates
https://issues.folio.org/browse/STCOM-590
Remove `columnWidths` prop from MCL …
> STCOM-590 ACQ Apps: MCL column width updates

- src/common/constants/constants.js
- src/components/PurchaseOrder/POForm.js
https://issues.folio.org/browse/UIOR-378 …
> UIOR-378 Template fix: Renewal Info accordion

- CHANGELOG.md
- package.json
- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/PiecesList.js
- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/ReviewDetails.js
https://issues.folio.org/browse/UIOR-386 …
> UIOR-386 cherry-pick the fix from bug fix branch

- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrdersLinesSearchConfig.js
- test/bigtest/network/config.js
- test/bigtest/tests/OrderLinesList/order-lines-test.js
- translations/ui-orders/en.json
Normalize ISBNs for ISBN Product ID searching in Order lines
https://issues.folio.org/browse/UIOR-274 …
> UIOR-274 Normalize and search ISBN product IDs

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20190925T150212

- src/common/POLFields/PhysicalFields/FieldMaterialSupplier.js
- src/components/CheckIn/FieldPieceFormat.js
- src/components/POLine/calculateEstimatedPrice.js
to fix warnings in the console …
> fix js console warnings

- src/common/POFields/FieldBillTo.js
- src/common/POFields/FieldPrefix.js
- src/common/POFields/FieldShipTo.js
- src/common/POFields/FieldSuffix.js
- src/common/POFields/FieldVendor.js
- src/common/POFields/RenewalFields/FieldRenewalInterval.js
- src/common/POLFields/DetailsFields/FieldAcquisitionMethod.js
- src/common/POLFields/DetailsFields/FieldOrderFormat.js
- src/common/POLFields/DetailsFields/FieldPaymentStatus.js
- src/common/POLFields/DetailsFields/FieldReceiptStatus.js
- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
- src/common/POLFields/FieldMaterialType.js
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/common/POLFields/VendorFields/FieldRefNumberType.js
- src/common/POLFields/VendorFields/FieldVendorAccountNumber.js
- src/components/CheckIn/AddPieceModal.js
- src/components/NotesForm/NotesForm.js
- src/components/POLine/Cost/FieldCurrency.js
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/PODetails/FieldOrderType.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/Summary/FieldWorkflowStatus.js
- src/components/PurchaseOrder/util.js
- src/components/Utils/Validate.js
- test/bigtest/network/factories/invoice.js
- test/bigtest/tests/line-details-other-test.js
- test/bigtest/tests/line-details-test.js
To be consistent we have to switch all fields that use `Select` on acq-component `FieldSelect`.
Also some warnings were removed regarding `label` attr in `FieldSelection` - `labelId` should be used …
> use common select component, remove console warnings

- translations/ui-orders/ar.json
> Update translation strings as of 20190927T125508

- src/common/constants/constants.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/settings/CreateInventoryForm.js
- src/settings/InventoryRecordTypeSelectField.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/POLineOtherResourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/POLinePhysicalForm.js
- test/bigtest/tests/OrderLinesList/order-lines-test.js
* added ISBN product type constant;
* Create Inventory should check to not sent empty values;
Small fixes and refactoring:
* render PO Line form only when order and create inventory setting have been loaded;
* add constant for ISBN product id type;
* make create inventory value required, to avoid sending empty string to the back-end;
Ideally all of the …
> add constant, fix createInventory setting fields

- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/asyncValidate.js
- test/bigtest/tests/POLine/line-edit-capture-inventure-uuid-test.js
- translations/ui-orders/en.json
Move ISBN Qualifier to separate field in UI Create/Edit screen
Move ISBN Qualifier to separate field in UI Create/Edit screen
https://issues.folio.org/browse/UIOR-392 …
> UIOR-392 Move ISBN Qualifier to separate field

- src/OrderLinesList/OrderLinesFilters.js
- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListFilters.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/interactors/orders.js
- test/bigtest/network/config.js
- test/bigtest/network/configs/configLines.js
- test/bigtest/network/configs/configOrders.js
- test/bigtest/network/configs/index.js
- test/bigtest/tests/OrderLinesList/order-lines-test.js
- test/bigtest/tests/orders-test.js
Change the PO/POL default filters to be empty
https://issues.folio.org/browse/UIOR-406 …
> UIOR-406 Change the PO/POL default filters to be empty

- translations/ui-orders/en.json
Fix error message
https://issues.folio.org/browse/UIOR-332 …
> UIOR-332 fix invalid label

- src/OrderLinesList/OrdersLinesSearchConfig.js
To support search if Qualifier field isn't empty
https://issues.folio.org/browse/UIOR-274 …
> UIOR-274 fix query to search product ids with qualifiers

- src/OrdersList/OrdersList.js
- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
Assign tags to Order Records
https://issues.folio.org/browse/UIOR-4
common component `withTags` usage …
> UIOR-4 Assign tags to Order Records

- package.json
- src/OrdersList/constants.js
- src/common/POFields/FieldVendor.js
- src/common/POFields/utils.js
- src/common/constants/constants.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/FieldOrderType.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/interactors/orders.js
- test/bigtest/interactors/settings/setting-prefixes.js
- test/bigtest/interactors/settings/setting-suffixes.js
- test/bigtest/tests/PurchaseOrder/close-order-modal-test.js
- test/bigtest/tests/add-line-test.js
- test/bigtest/tests/create-order-test.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/edit-order-test.js
- test/bigtest/tests/order-approve-test.js
- test/bigtest/tests/order-details-with-line-test.js
Remove some TODOs
While it's helpful for reviewers to help identify potential problems, …
> fix tests, bump up okapi interfaces

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
fix initial values of create OT form …
> UIOR-390 fix OT creation

- src/components/POLine/validate.js
Add validation of 100% distributed amount
https://issues.folio.org/browse/UIOR-370
While …
> UIOR-370 fix validation

- src/OrderLinesList/Details/Details.js
- src/components/CheckIn/CheckIn.js
- src/components/Panes/Panes.js
- src/index.js
- src/settings/OrderTemplates/OrderTemplates.js
> fix router imports

- src/OrderLinesList/Details/OrderLineDetails.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
To display, assign, unassign, and output tags associated with individual ORDER LINE records within the FOLIO Orders app.
https://issues.folio.org/browse/UIOR-5
Use `Tags` from `stripes-acq-components` …
> UIOR-5 Assign tags to Order Line Records

- src/common/OpenedRequestsModal/OpenedRequestsModal.css
- src/common/OpenedRequestsModal/OpenedRequestsModal.js
- src/common/OpenedRequestsModal/index.js
- src/components/CheckIn/CheckInDetails.js
- src/components/CheckIn/ItemsListModal.js
- src/components/Receiving/ItemDetails.js
- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReviewDetails.js
- src/components/Receiving/util.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
- test/bigtest/network/config.js
- test/bigtest/network/configs/configRequests.js
- test/bigtest/network/configs/index.js
- test/bigtest/network/factories/request.js
- test/bigtest/network/models/request.js
- test/bigtest/network/serializers/request.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-377 …
> UIOR-377 Show indicator of open requests during receiving and check-in

- src/OrderLinesList/OrderLinesFilters.js
- src/OrderLinesList/OrdersLinesFilterConfig.js
- src/OrderLinesList/constants.js
- test/bigtest/network/config.js
https://issues.folio.org/browse/UIOR-275 …
> UIOR-275 Filter order lines by Tags

- src/common/POLFields/VendorFields/FieldRefNumberType.js
- src/common/POLFields/VendorFields/FieldVendorRefNumber.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/POLineVendorForm.js
- Order templates are preventing the changing of POL order format
- Add `Required` prop to vendor ref number and vendor ref number type in POL Form
- Remove validation for  vendor ref number and vendor ref number type  from template form
https://issues.folio.org/browse/UIOR-391
Ideally all of the PRs involved in breaking changes would be merged in the …
> UIOR-391 Templates prevent the changing PO format

- src/common/OpenedRequestsModal/OpenedRequestsModal.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-377 …
> UIOR-377 fix close button label on opened requests modal

- package.json
- src/components/Utils/api.js
- src/components/Utils/resources.js
since we use funds from the business layer
https://issues.folio.org/browse/UIF-72
While …
> UIF-72 use funds from BL

- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
https://issues.folio.org/browse/UIOR-418
common component usage …
> UIOR-418 Orders: Update 'save and close' and 'Cancel' Buttons - UX

- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/Utils/getIdentifierTypesForSelect.js
- test/bigtest/interactors/line-edit-page.js
Component of product ids form was re-written to the functional and to use `RepeatableField` common component.
Reduce the identifier types in the POL dropdown list
https://issues.folio.org/browse/UIOR-414 …
> UIOR-414 reduct product id types

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/POLine/Vendor/VendorForm.js
FOLIO is adopting a four-column layout for Edit forms. This will reduce the amount of scrolling required in longer records.
https://issues.folio.org/browse/UIOR-420 …
> UIOR-420 Update POL layout for create and edit

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/const.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/constants.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateTagsView/OrderTemplateTagsView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateTagsView/index.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/constants.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-342 …
> UIOR-342 Add PO and PO Line tags to the Order Template

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.css
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-342 …
> UIOR-342 fix layout for tags on OT form

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20191028T151017

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/components/Utils/resources.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/line-edit-test.js
- translations/ui-orders/en.json
To reduce the number of clicks to open POs once they have been created. If a library is using single line POs, and does not require approval before opening, then have a setting that allows for the PO to be saved and opened all at once.
https://issues.folio.org/browse/UIOR-281
Check  `isOpenOrderEnabled` setting, order `workflowStatus` and `approved` …
> UIOR-281 Save and Open PO from POL create/edit

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
Add Acq Unit to the Order Template
https://issues.folio.org/browse/UIOR-340
While it's …
> UIOR-340 add Acq units on order template form

- src/common/utils/getSettingsList.js
https://issues.folio.org/browse/UIOR-416 …
> UIOR-416 fix pref/suf alph order case ins

- package.json
> Add missed interfaces

- PULL_REQUEST_TEMPLATE.md
- package.json
- src/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- translations/ui-orders/en.json
fix permission error, so any user with orders settings can manipulate of order templates
https://issues.folio.org/browse/UIOR-341 …
> UIOR-341 fix permissions error

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineForm.js
> remove unwanted "Leave form" modal

- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/PiecesList.js
- src/components/POLine/POLineInvoices/POLineInvoices.js
- src/components/PurchaseOrder/POInvoices/POInvoices.js
- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReceivingList.js
- src/components/Receiving/ReviewDetails.js
Receiving data input modal is too dark
https://issues.folio.org/browse/UIOR-423
While it's …
> UIOR-423 Receiving data input modal is too dark

- package.json
- test/bigtest/tests/save-updated-line-test.js
add missing perms to package.json
https://issues.folio.org/browse/UIOR-341
While it's …
> UIOR-341 fix missing perms 2

- package.json
add missed perm acquisitions-units.units.collection.get …
> add missed perm 3 - acquisitions-units.units.collection.get

- translations/ui-orders/ar.json
> Update translation strings as of 20191106T134035

- src/components/POLine/Item/ItemForm.css
- src/components/POLine/Item/ItemForm.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/POLine/line-edit-capture-inventure-uuid-test.js
- translations/ui-orders/en.json
The interface should not display UUIDs to the user. In this case the user just needs to know if there is an existing instance linked or not
https://issues.folio.org/browse/UIOR-430 …
> UIOR-430 POL item details: Replace instance UUID with user friendly message

- src/components/LayerCollection/LayerPOLine.js
remove Dirty form message appearing when clicking "Save and open order"
https://issues.folio.org/browse/UIOR-443 …
> UIOR-443 remove dirty message

- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
https://issues.folio.org/browse/UIOR-434 …
> UIOR-434 Resequence the accordions in the POL View and Create/Edit Screens

- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-435 …
> UIOR-435 Resequence the POL accordions in the Order template

- karma.conf.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/components/PurchaseOrder/renewals/RenewalsForm.js
- src/components/PurchaseOrder/util.js
- test/bigtest/tests/POLine/line-edit-capture-inventure-uuid-test.js
- test/bigtest/tests/POLine/line-notes-test.js
https://issues.folio.org/browse/UIOR-448 …
> UIOR-448 PO/POL fields are editable for closed orders

- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-442 …
> UIOR-442 Creating 2nd PO automatically doesn't work

- test/bigtest/tests/add-Line-button-for-closed-orders-test.js
- test/bigtest/tests/add-Line-button-for-open-orders-test.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/receiving-history-from-closed-order-test.js
- test/bigtest/tests/receiving-list-test.js
> break apart some tests

- package.json
for not diku-admin there are some missing permissions …
> add missed perms

- src/common/constants/defaultCloseOrderReasons.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-452 …
> UIOR-452 Add Canceled as reason for closure

- src/components/POLine/Item/ItemForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-451 …
> UIOR-451 Item details: not connected message

- src/components/Utils/resources.js
- src/settings/OrderNumberModifier/OrderNumberModifier.js
fix prefixes/suffixes loading
While it's helpful for reviewers to help identify potential …
> (fix) prefixes/suffixes are not loaded

- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- translations/ui-orders/en.json
Cancel button on PO and POL form is now labeled "Close"
https://issues.folio.org/browse/UIOR-455 …
> UIOR-455 PO and POL change button label

- Jenkinsfile
- test/bigtest/index.js
- test/bigtest/interactors/check-in-history-page.js
- test/bigtest/interactors/check-in-items-page.js
- test/bigtest/interactors/const.js
- test/bigtest/interactors/line-details-page.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/interactors/note-form-page.js
- test/bigtest/interactors/note-view-page.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/interactors/orders.js
- test/bigtest/interactors/receiving-history-page.js
- test/bigtest/interactors/receiving-page.js
- test/bigtest/interactors/settings/ClosingReasons/ClosingReasons.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplateView.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesEditor.js
- test/bigtest/interactors/settings/OrderTemplates/OrderTemplatesList.js
- test/bigtest/interactors/settings/settings.js
- test/bigtest/tests/OrderLinesList/line-details-other-test.js
- test/bigtest/tests/check-in-items-test.js
- test/bigtest/tests/line-details-other-test.js
- test/bigtest/tests/line-details-test.js
- test/bigtest/tests/settings/closing-reasons-test.js
to avoid falsy test failures
While it's helpful for reviewers to help identify potential …
> leverage test timeout time to constant

- src/components/CheckIn/CheckInDetails.js
- src/components/Receiving/ItemDetails.js
- src/components/Receiving/ReviewDetails.js
In receiving piece screen, keep copies for the same location next to each other
https://issues.folio.org/browse/UIOR-248 …
> UIOR-248 In receiving piece screen, keep copies for the same location next to each other

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20191122T195518

- src/common/utils/getPieceStatusFromItem.js
Basically, it handles a special case , when Item isn't created, but as itemStatus is a required field on the back-end - we sent them an empty string
https://issues.folio.org/browse/UIOR-376
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> UIOR-376 handle no item and empty status

- src/components/PurchaseOrder/LineListing/LineListing.js
Per Dennis, it would be great to have End of List marker for the list of PO Lines
https://issues.folio.org/browse/UIOR-284 …
> UIOR-284 add end of the list marker

- src/common/constants/itemStatuses.js
- src/common/utils/getPieceStatusFromItem.js
when there is no item we should use something like "Undefined"
https://issues.folio.org/browse/UIOR-376 …
> UIOR-376 use Undefined if no item

- translations/ui-orders/en.json
> UIOR-376 add translation

- src/components/POLine/Item/ItemForm.js
https://issues.folio.org/browse/UIOR-451 …
> UIOR-451 Fix Item details - Title

- src/components/Utils/order/showUpdateOrderError.js
- translations/ui-orders/en.json
When creating transactions based on orders the system will need to check in their is enough money in the desired budget to cover the amount of the transaction and notify the user if there isn't.
https://issues.folio.org/browse/UIOR-431 …
> UIOR-431 Prevent encumbering with Funds that have insufficient amounts to cover distribution

- src/components/POLine/Item/ItemForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
remove warning, and fix Create template …
> fix create template, remove warning

- package.json
> fix tests (bigtest)

- .eslintrc
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- package.json
- src/components/POLine/POLineInvoices/POLineInvoicesContainer.js
- src/components/PurchaseOrder/POInvoices/POInvoicesContainer.js
- src/settings/InstanceType/InstanceType.js
https://issues.folio.org/browse/UIOR-440 …
> Release v1.8.0

- CHANGELOG.md
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-462 …
> UIOR-462 Cannot fill in any of the cost detail fields in Order Templates

- src/components/POLine/Cost/CostForm.js
- translations/ui-orders/en.json
Not negative validation usage from stripes-acq-components …
> Not negative validation from stripes-acq-components

- CHANGELOG.md
- src/components/Utils/resources.js
https://issues.folio.org/browse/UINV-96 …
> UINV-96 Closing reasons are not loaded

- src/components/Utils/const.js
- src/components/Utils/resources.js
- src/settings/ClosingReasons/ClosingReasonsContainer.js
> refactor(UINV-96) use constants for closing reason config

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
- src/components/POLine/POLineForm.js
- src/components/POLine/calculateEstimatedPrice.js
- src/components/POLine/validate.js
- src/components/Utils/parseMoney.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- translations/ui-orders/en.json
Calculation of estimated price in cost details sometimes blocks POLs from being created/saved.
It's because JS handles math with floating point poorly. We have to use common functions from stripes-acq-components to handle money numbers in a right way.
https://issues.folio.org/browse/UIOR-464 …
> UIOR-464 fix Calculation of estimated price

- CHANGELOG.md
- src/OrdersList/OrdersList.js
- src/OrdersList/utils.js
- src/common/utils/getUserNameById.js
- src/common/utils/index.js
- src/components/LayerCollection/LayerPO.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/PODetails/UserValue.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
https://issues.folio.org/browse/UIOR-470 …
> UIOR-470 Users is requested with MAX_INT limit which requests all users

- .eslintignore
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- package.json
Patch release for orders
https://issues.folio.org/browse/UIOR-469 …
> Release v1.8.1

- src/components/POLine/Cost/CostView.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
Capture cost information and fund distributions in the currency selected at POL
https://issues.folio.org/browse/UIOR-460
to pass `currency` selected in line down to the fund distribution components
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIOR-460 pass Line's `currency` to Fund distribution component

- CHANGELOG.md
- src/components/POLine/Cost/CostView.js
https://issues.folio.org/browse/UIOR-460 …
> UIOR-460 fix display of listUnitPriceElectronic

- CHANGELOG.md
- src/components/POLine/Cost/FieldCurrency.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
Also to use all currencies if Vendor's currencies aren't specified
https://issues.folio.org/browse/UIOR-381 …
> UIOR-381 fix template to use Vendor's currencies

- src/components/POLine/Cost/CostForm.js
https://issues.folio.org/browse/UIOR-460 …
> UIOR-460 fix floating point in discount

- src/common/constants/defaultCloseOrderReasons.js
https://issues.folio.org/browse/BF-163 …
> BF-163 remove special char

- CHANGELOG.md
- src/components/POLine/POLineInvoices/POLineInvoices.js
- src/components/POLine/POLineInvoices/POLineInvoicesContainer.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POInvoices/POInvoices.js
- src/components/PurchaseOrder/POInvoices/POInvoicesContainer.js
- src/components/Utils/resources.js
Refactoring of related invoices components to reload fresh data always in functional style
https://issues.folio.org/browse/UIOR-478 …
> UIOR-478 Invoices from the previous order is shown

- package.json
Fix missing permissions for order settings
https://issues.folio.org/browse/BF-165
While it's …
> BF-165 fix settings permissions

- package.json
found missing permissions if viewing invoice
https://issues.folio.org/browse/UIOR-478
While …
> UIOR-478 add permissions to fetch history for related invoices

- CHANGELOG.md
- src/components/CheckIn/CheckInItemsWrapper.js
"Check-in error" when using "Check-in" in "Add piece" modal
https://issues.folio.org/browse/UIOR-485 …
> UIOR-485 set missing item status

- CHANGELOG.md
- package.json
Create UIOR bugfix release
https://issues.folio.org/browse/UIOR-473 …
> Release v1.8.2

- CHANGELOG.md
- src/components/CheckIn/ItemsListModal.js
- src/components/CheckIn/util.js
- src/components/Receiving/ItemDetails.js
- src/components/Receiving/LineDetails.js
- src/components/Receiving/ReceivingHistory.js
- src/components/Receiving/ReviewDetails.js
- src/components/Receiving/util.js
- translations/ui-orders/en.json
Add or update call number during receiving/checkin
https://issues.folio.org/browse/UIOR-432 …
> UIOR-432 Add or update call number

- src/components/Receiving/ItemDetails.js
https://issues.folio.org/browse/UIOR-432 …
> UIOR-432 fix callNumber

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200103T213225

- src/components/CheckIn/util.js
https://issues.folio.org/browse/UIOR-432 …
> UIOR-432 fix callNumber for checkIn

- src/components/CheckIn/CheckInItemsActions.js
Use new Dropdown API to remove console warnings …
> use new Dropdown API to remove console warnings

- src/OrderLinesList/Details/OrderLineDetails.js
- src/common/OrdersCheckboxFilter/OrdersCheckboxFilter.js
- src/components/PurchaseOrder/UpdateOrderErrorModal/UpdateOrderErrorModal.js
to remove extra warnings in console …
> remove extra warnings in console

- src/components/Utils/order/showUpdateOrderError.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-431 …
> UIOR-431 Update error code

- src/OrderLinesList/OrdersLinesSearchConfig.js
- src/common/POLFields/DetailsFields/FieldCheckInItems.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-239 …
> UIOR-239 Add "Package" checkbox

- translations/ui-orders/en.json
Update translation for `titleOrPackage` search option label …
> Missed translation

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200127T201424

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-494 …
> UIOR-494 Update settings permission label

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-472 …
> UIOR-472 Display encumbered value on POL for orders made in currency other than system currency

- CHANGELOG.md
- src/OrderLinesList/Details/OrderLineDetails.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/Other/OtherView.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
- src/components/POLine/Physical/PhysicalView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
https://issues.folio.org/browse/UIOR-358 …
> UIOR-358 Vendor doesn't display in purchase order even though assigned

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/calculateEstimatedPrice.js
- src/components/POLine/calculateEstimatedPrice.test.js
- src/components/POLine/validate.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
> calculateEstimatedPrice unit tests

- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
Error is displayed on UI, that the order failed to close
https://issues.folio.org/browse/UIOR-333 …
> UIOR-333 add toast

- CHANGELOG.md
- src/OrdersList/OrdersListSearchConfig.js
add placeholders to the Date search fileds
https://issues.folio.org/browse/UIOR-303
While …
> UIOR-303 add indexes with date format

- CHANGELOG.md
- src/common/resources/instanceStatuses.js
- src/common/resources/instanceTypes.js
- src/common/resources/loanTypes.js
Instance status, Instance type, Loan type dropdown lists in the Order settings are not in alphabetical order
https://issues.folio.org/browse/UIOR-504 …
> UIOR-504 Fix the alphabetical order

- CHANGELOG.md
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.css
- src/components/PurchaseOrder/PO.js
Move record action buttons into "Action" button UX pattern
https://issues.folio.org/browse/UIOR-509 …
> UIOR-509 Move record action buttons into "Action" button UX pattern

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/FieldCurrency.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- test/bigtest/tests/line-edit-test.js
- test/bigtest/tests/save-updated-line-test.js
Use system default currency as default POL currency (Remove org limit)
https://issues.folio.org/browse/UIOR-505 …
> UIOR-505 Use system currency as default for POL

- CHANGELOG.md
- package.json
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/Summary/FieldWorkflowStatus.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/components/PurchaseOrder/getPOActionMenu.js
- src/components/PurchaseOrder/util.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/PurchaseOrder/reopen-order-has-button-test.js
- translations/ui-orders/en.json
Ability to "Reopen" and once again "Close" purchase orders
https://issues.folio.org/browse/UIOR-457 …
> UIOR-457 Ability to "Reopen" and once again "Close" purchase orders

- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/line-create-test.js
Tests for POL currency
While it's helpful for reviewers to help identify potential problems, …
> Tests for POL currency

- test/bigtest/tests/POLine/line-create-empty-vendor-test.js
Fix currency test
While it's helpful for reviewers to help identify potential problems, …
> Fix currency test

- src/common/POFields/FieldOrganization.js
https://issues.folio.org/browse/UIOR-506 …
> UIOR-506 Replace org selection components with organization lookup - fix validation

- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/getPOActionMenu.js
Move Delete button at the bottom per request from PO in the comment
https://issues.folio.org/browse/UIOR-509 …
> UIOR-509 move Delete at the bottom

- src/OrdersList/OrdersListFilters.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Cost/FieldCurrency.js
* fix when currency value is cleared in template - it should pre-select value of platform;
* use Selection with search due to large currency options list;
*remove console warning of the not unique id;
https://issues.folio.org/browse/UIOR-505 …
> UIOR-505 fix clear of currency in template

- src/components/POLine/Cost/FieldCurrency.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/line-create-test.js
We have to fix the test since used component has been changed …
> UIOR-505 fix test

- package.json
- src/common/Notes/NoteView.js
- src/common/POFields/FieldOrganization.js
- src/common/POFields/RenewalFields/FieldRenewalDate.js
- src/common/POFields/RenewalFields/FieldRenewalInterval.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- test/bigtest/index.js
- test/bigtest/interactors/note-form-page.js
- test/bigtest/interactors/note-view-page.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/interactors/order-edit-page.js
- test/bigtest/tests/POLine/line-notes-test.js
- test/bigtest/tests/create-order-test.js
- test/bigtest/tests/line-edit-test.js
- test/bigtest/tests/order-open-disabled-test.js
- test/bigtest/tests/order-open-test.js
> BigTest fixes

- package.json
> UIOR-471 Update orders OKAPI interface

- package.json
> upgrade stripes to v3

- package.json
> fix react-router version for BigTest

- package.json
- src/components/LayerCollection/LayerPOLine.js
> Use common callout context

- package.json
- test/bigtest/network/serializers/item.js
- test/bigtest/network/serializers/request.js
> remove obsolete dep

- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-521 …
> UIOR-521 New icon for "Close order"

- CHANGELOG.md
> Add changelog to UIOR-521

- src/OrderLinesList/OrderLinesFilters.js
https://issues.folio.org/browse/UIREC-60 …
> UIREC-60 Improve Location filter on the Titles list to use location look-up

- CHANGELOG.md
- package.json
- src/components/POLine/POLineView.js
https://issues.folio.org/browse/UIOR-517 …
> Release v2.0.0

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200314T132532

- CHANGELOG.md
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-529 …
> UIOR-529 New icon for "Open order"

- translations/ui-orders/ru.json
> Update translation strings as of 20200316T134017

- src/OrdersList/OrdersList.js
- src/common/ClosingReasonFilter/ClosingReasonFilter.js
- src/common/hooks/index.js
- src/common/hooks/useCloseReasonOptions.js
- src/common/utils/getClosingReasonsOptions.js
- src/common/utils/index.js
- src/components/PurchaseOrder/CloseOrder/CloseOrderModal.js
- src/components/PurchaseOrder/PO.js
Recently was introduced a ridiculous amount of console warnings regarding `undefined` translations, this is the fix  …
> reduce console warnings, leverage code in one place

- src/common/hooks/useCloseReasonOptions.js
> fix error after page refreshed and user returns to the orders list

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200331T152557

- translations/ui-orders/pt_BR.json
> Update translation strings as of 20200403T124750

- CHANGELOG.md
- package.json
Permission issue with Orders: create order
https://issues.folio.org/browse/UIOR-543
While …
> UIOR-543 Permission issue with Orders: create order

- src/components/PurchaseOrder/PO.js
show close details pane button after order is created
https://issues.folio.org/browse/UIOR-543 …
> UIOR-543 show close pane button

- translations/ui-orders/ar.json
- translations/ui-orders/ur.json
> Update translation strings as of 20200406T162815

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
to remove code smell
While it's helpful for reviewers to help identify potential problems, …
> remove code smell

- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrderLinesListContainer.js
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListContainer.js
fix first click on Loadmore doesn't trigger fetching, only shows spinner
https://issues.folio.org/browse/UIOR-516 …
> UIOR-516 fix first click on loadMore and add margins

- translations/ui-orders/fr_FR.json
- translations/ui-orders/pt_BR.json
> Update translation strings as of 20200409T134057

- src/OrderLinesList/Details/OrderLineDetails.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
When selecting new records in the orders app, approving, opening, closing or cloning an order a loading icon displays in the view pane until the action is complete
https://issues.folio.org/browse/UIOR-540 …
> UIOR-540 refactoring of PO container

- CHANGELOG.md
- src/components/PurchaseOrder/LineListing/LineListing.js
Align actions icons in table to right hand side of view pane(s)
https://issues.folio.org/browse/UINV-138 …
> UINV-138 add right arrow

- CHANGELOG.md
- package.json
- src/components/POLine/Item/ProductIdDetailsForm.js
https://issues.folio.org/browse/UIOR-552 …
> UIOR-552 Can not remove product ID without disconnecting instance

- src/components/LayerCollection/LayerPOLine.js
> UIOR-552 remove unnecessary laoding of funds

- src/components/POLine/Item/ItemForm.js
to handle exception cases and always overwrite data coming from instance
https://issues.folio.org/browse/UIOR-554 …
> UIOR-554 fix selecting instance exceptions

- CHANGELOG.md
- src/components/POLine/Item/InstancePlugin.js
- src/components/POLine/Item/ItemForm.css
- src/components/POLine/Item/ItemForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-555 …
> UIOR-555 Refine styling of Title field at PO Line form

- CHANGELOG.md
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/components/PurchaseOrder/Summary/TotalEncumberedValue/TotalEncumberedValue.js
- src/components/PurchaseOrder/Summary/TotalEncumberedValue/index.js
- test/bigtest/interactors/order-details-page.js
- test/bigtest/tests/details-order-test.js
- test/bigtest/tests/order-details-with-line-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-518 …
> UIOR-518 Display "Total encumbered" in PO summary

- CHANGELOG.md
- src/common/POFields/FieldPrefix.js
- src/common/POFields/FieldSuffix.js
- src/components/LayerCollection/LayerPO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/orderResource.js
- test/bigtest/interactors/order-edit-page.js
https://issues.folio.org/browse/UIOR-495 …
> UIOR-495 Populate poNumberPrefix & poNumberSuffix fields on order creation

- CHANGELOG.md
- src/common/POLFields/DetailsFields/FieldOrderFormat.js
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- test/bigtest/interactors/line-edit-page.js
- test/bigtest/tests/POLine/line-create-test.js
- test/bigtest/tests/line-create-test.js
Disable Buttons after user clicks "Save and Close" or "Save and open purchase order"
https://issues.folio.org/browse/UIOR-539 …
> UIOR-539 show spinner when saving in process

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-553 …
> Release v2.0.4

- src/components/POLine/Cost/CostView.js
- test/bigtest/network/config.js
- test/bigtest/network/configs/configTemplates.js
- test/bigtest/network/configs/index.js
- test/bigtest/tests/settings/OrderTemplates/order-templates-view-test.js
> Fix bigtest mirage config for order templates

- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151 …
> UIORGS-151 using the same Expand/Collapse

- src/components/LayerCollection/LayerPO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/Utils/orderResource.js
https://issues.folio.org/browse/UIOR-495 …
> UIOR-495 fix poNumber suffix and prefix usage

- package.json
> bump up invoice interface version

- CHANGELOG.md
- test/bigtest/interactors/modal.js
- test/bigtest/tests/settings/setting-prefixes-test.js
- test/bigtest/tests/settings/setting-suffixes-test.js
https://issues.folio.org/browse/UIOR-497 …
> UIOR-497 Prevent deletion of prefix/suffix values that are in use

- CHANGELOG.md
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineView.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/util.js
https://issues.folio.org/browse/UIOR-453
Allow user to edit 
- Vendor when PO is Open
- Bill to when PO is Open
- Ship to when PO is Open
- Material supplier and Access provider on POL when PO is open
- **Could be merged after  [MODORDERS-336](https://github.com/folio-org/mod-orders/pull/292)** …
> UIOR-453 Ability to change Vendor and Bill to and Ship to without closing order

- CHANGELOG.md
- src/OrdersList/OrdersListFilters.js
- src/OrdersList/OrdersListFiltersContainer.js
https://issues.folio.org/browse/UIREC-42
Use updated `AcqUnitFilter` from `stripes-acq-components` …
> UIREC-42 Filter by Acq unit

- src/components/PurchaseOrder/PO.js
> use `replace` instead of `push` to prevent user go back to deeted order

- src/components/Utils/order/showUpdateOrderError.js
link in toast was broken after upgrade to stripes v4
https://issues.folio.org/browse/UIOR-559 …
> UIOR-559 fix link in toast

- CHANGELOG.md
- src/components/PurchaseOrder/POForm.js
- src/components/Utils/orderResource.js
basically, the validation wasn't working for a while. This is a fix for master branch, however it might differ for Q1 release hotfix, since there was no prefix and suffix editable fields
https://issues.folio.org/browse/UIOR-562
connected with https://github.com/folio-org/ui-orders/pull/192
Ideally all of the PRs involved in breaking changes would be merged …
> UIOR-562 fix order number field validation

- .eslintrc
- CHANGELOG.md
- package.json
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/order/showUpdateOrderError.js
- src/components/Utils/orderResource.js
- src/settings/OrderTemplates/OrderTemplates.js
- show proper user on Create order form;
- don't throw an exception if callout is not available (basically this is a root of evil here when nothing happens after click on Save);
https://issues.folio.org/browse/UIOR-562 …
> UIOR-562 fix callout exceptions, previous username

- CHANGELOG.md
- src/components/Utils/orderResource.js
- test/bigtest/tests/create-ongoing-order-test.js
https://issues.folio.org/browse/UIOR-565
- add prop `ongoing : {}` for ongoing order type 
- remove prop `ongoing` from one-time order type …
> UIOR-565 Ongoing order not saving

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200515T182823

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200521T142352

- src/components/POLine/Item/PackagePoLineField/PackagePoLineField.js
https://issues.folio.org/browse/UIOR-564 …
> UIOR-564 fix lookup package line button

- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplates.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
* enable fund code filling for the back-end.
* moved setting initial state to constructor;
* removed usage of CalloutContext since it can cause exceptions;
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> fill fund code

- translations/ui-orders/ru.json
> Update translation strings as of 20200522T132417

- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-564 …
> UIOR-564 Update en.json

- CHANGELOG.md
- package.json
- src/common/constants/errorCodes.js
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/ModalDeletePieces/ModalDeletePieces.js
- src/components/ModalDeletePieces/ModalDeletePiecesContainer.js
- src/components/ModalDeletePieces/getHydratedPieces.js
- src/components/ModalDeletePieces/index.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/order/showUpdateOrderError.js
- test/bigtest/interactors/delete-pieces-modal.js
- test/bigtest/interactors/index.js
- test/bigtest/interactors/order-lines.js
- test/bigtest/interactors/orders.js
- test/bigtest/network/config.js
- test/bigtest/tests/POLine/line-edit-open-status-test.js
- test/bigtest/tests/Utils/order/show-update-order-error-test.js
- translations/ui-orders/en.json
Ability to change quantity ordered without closing order
https://issues.folio.org/browse/UIOR-444 …
> UIOR-444 initial commit

- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/util.js
Ability to change quantity ordered without closing order
https://issues.folio.org/browse/UIOR-444 …
> UIOR-444 enable change quantity on open order

- CHANGELOG.md
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/POLineForm.js
Ability to change price and fund distribution information without closing order
https://issues.folio.org/browse/UIOR-433 …
> UIOR-433 Ability to change price and fund distribution

- test/bigtest/interactors/CalloutInteractor.js
- test/bigtest/interactors/index.js
- test/bigtest/tests/PurchaseOrder/clone-order-test.js
- test/bigtest/tests/line-edit-test.js
https://issues.folio.org/browse/UIOR-567 …
> UIOR-567 add tests for callouts

- CHANGELOG.md
- src/components/LayerCollection/LayerPO.js
- src/components/PurchaseOrder/PO.js
- test/bigtest/tests/settings/setting-prefixes-test.js
fix error modal close exception after clone order clicked and error access to acq unit
https://issues.folio.org/browse/UIOR-567 …
> UIOR-567 fix error modal close exception

- src/OrderLinesList/Details/OrderLineDetails.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
> UIOR-567 fix missing callouts

- package.json
> try fix tests

- src/components/PurchaseOrder/PO.js
- test/bigtest/tests/order-open-test.js
> fix tests 3

- CHANGELOG.md
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineLocationsForm/POLineLocationsForm.js
https://issues.folio.org/browse/UIOR-530 …
> UIOR-530 Improve Select location dropdown to use only select Location plugin

- CHANGELOG.md
- package.json
> backport 2.0.5 release

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/POLineForm.js
these changes are related to UIOR-569 instead of UIOR-433, no sense to introduce them before back-end is implemented. …
> UIOR-433 revert

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
https://issues.folio.org/browse/UIOR-417 …
> UIOR-417 Retain filters when switching from PO to POL and back

- CHANGELOG.md
- src/common/OrdersTextFilter/OrdersTextFilter.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/PurchaseOrder/OngoingOgderInfo/OngoingOrderInfoView.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/Summary/SummaryView.js
https://issues.folio.org/browse/UIOR-524 …
> UIOR-524 Form elements must have labels

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrderLinesListContainer.js
- src/OrderLinesList/utils.js
https://issues.folio.org/browse/UIOR-572 …
> UIOR-572 display fund codes from fundDistribution

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200618T161121

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200623T182030

- translations/ui-orders/ru.json
> Update translation strings as of 20200624T182544

- CHANGELOG.md
- src/OrderLinesList/OrderLinesFilters.js
Claim filters not working - hide filters
https://issues.folio.org/browse/UIOR-578
While it's …
> UIOR-578 hide Claim filters

- CHANGELOG.md
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/POLineForm.js
Ability to change price and fund distribution information for Open order
https://issues.folio.org/browse/UIOR-569
Reverts folio-org/ui-orders#892
> UIOR-569 Revert "UIOR-433 revert"

- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-581 …
> UIOR-581 show correct messsage

- src/OrdersList/OrdersListFilterConfig.js
POL displays in filter results even though order is open and displays no reason for closure.
https://issues.folio.org/browse/UIOR-576 …
> UIOR-576 fix search by reason for closure

- CHANGELOG.md
- package.json
> backport release v2.1.1

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200709T123052

- CHANGELOG.md
- src/OrderLinesList/OrderLinesFilters.js
- src/components/POLine/POLineView.js
- translations/ui-orders/en.json
Add POL number to the POL details header
https://issues.folio.org/browse/UIOR-585
While it's …
> UIOR-585 Add POL number to the POL details header

- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/fr.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
> Update translation strings as of 20200710T132222

- CHANGELOG.md
- package.json
- src/common/FundFilter/FundFilter.test.js
- src/components/POLine/Cost/FieldCurrency.js
https://issues.folio.org/browse/UISACQCOMP-2 …
> UISACQCOMP-2 currency select values are not translated

- CHANGELOG.md
- package.json
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/common/POLFields/FieldsLocation/validate.js
- src/common/utils/createOnChangeSelectionFilter.js
- src/common/utils/index.js
- src/components/POLine/Location/LocationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
https://issues.folio.org/browse/UIOR-590 …
> UIOR-590 Missing asterisk on location quantity fields

- CHANGELOG.md
- src/components/POLine/const.js
https://issues.folio.org/browse/STCOM-655 …
> STCOM-655 remove duplicated id

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIF-213 …
> UIF-213 Select expense class for Order Fund distribution

- CHANGELOG.md
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-520 …
> UIOR-520 New icon for "Clone"

- CHANGELOG.md
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIREC-58 …
> UIREC-58 New icon for Receive

- CHANGELOG.md
- package.json
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-589 …
> UIOR-589 hide from user permission UI: Orders

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200813T135432

- CHANGELOG.md
- src/settings/Prefixes/Prefixes.js
- src/settings/Suffixes/Suffixes.js
- src/settings/utils.js
- test/bigtest/tests/line-edit-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-583 …
> UIOR-583 Validation for suffix and prefix name

- src/OrdersList/constants.js
- src/common/POLFields/DetailsFields/FieldPaymentStatus.js
- src/common/POLFields/index.js
- src/common/constants/api.js
- src/common/hooks/useHandleOrderUpdateError/index.js
- src/common/hooks/useHandleOrderUpdateError/useHandleOrderUpdateError.js
- src/components/LayerCollection/LayerPO.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/Utils/order/showUpdateOrderError.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- test/bigtest/tests/Utils/order/show-update-order-error-test.js
- translations/ui-orders/en.json
error message for inactive class
https://issues.folio.org/browse/UIF-213 …
> UIF-213 add error message for inactive class

- CHANGELOG.md
- src/components/NotesForm/NotesForm.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
https://issues.folio.org/browse/UIOR-597 …
> UIOR-597 fix tags refresh

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200817T131718

- translations/ui-orders/en.json
- translations/ui-orders/en_US.json
> UIF-213 update error message

- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
https://issues.folio.org/browse/UIOR-597 …
> UIOR-597 don't show spinner on tags save

- CHANGELOG.md
- src/common/POLFields/EresourcesFields/FieldURL.js
- src/common/POLFields/index.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Eresources/EresourcesView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-556 …
> UIOR-556 Add URL to Electronic format data

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20200820T141724

- CHANGELOG.md
- src/components/POLine/POLineForm.js
https://issues.folio.org/browse/UIOR-601 …
> UIOR-601 fix set template values for existing order

- translations/ui-orders/zh_CN.json
> Update translation strings as of 20200827T215834

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemView.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.js
https://issues.folio.org/browse/UIOR-604 …
> UIOR-604 Update layout of data on the POL

- CHANGELOG.md
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
https://issues.folio.org/browse/UIOR-603 …
> UIOR-603 Update order record data layout

- src/components/PurchaseOrder/PODetails/PODetailsForm.js
https://issues.folio.org/browse/UIOR-603 …
> UIOR-603 Update order form layout

- CHANGELOG.md
- src/components/POLine/Eresources/EresourcesView.js
https://issues.folio.org/browse/UIOR-600 …
> UIOR-600 Make URL in e-resource a hyperlink

- package.json
> update erm interface

- CHANGELOG.md
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-608 …
> UIOR-608 Update POL Cost detail accordion

- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
- src/common/POLFields/EresourcesFields/FieldExpectedActivation.js
- src/common/POLFields/EresourcesFields/FieldURL.js
- src/common/POLFields/EresourcesFields/FieldUserLimit.js
- src/common/POLFields/FieldMaterialType.js
- src/common/POLFields/VendorFields/FieldVendorAccountNumber.js
- src/common/POLFields/VendorFields/FieldVendorRefNumber.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Item/TitleField/TitleField.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/settings/InventoryRecordTypeSelectField.js
- test/bigtest/tests/POLine/line-edit-open-status-test.js
https://issues.folio.org/browse/UIOR-607 …
> UIOR-607 missed fields

- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_US.json
- translations/ui-orders/fr.json
- translations/ui-orders/he.json
- translations/ui-orders/hi_IN.json
- translations/ui-orders/hu.json
- translations/ui-orders/ja.json
- translations/ui-orders/ko.json
- translations/ui-orders/pl.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
> Update translation strings as of 20200928T202231

- translations/ui-orders/en.json
> UIOR-608 fix translation

- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_US.json
- translations/ui-orders/fr.json
- translations/ui-orders/he.json
- translations/ui-orders/hi_IN.json
- translations/ui-orders/hu.json
- translations/ui-orders/ja.json
- translations/ui-orders/ko.json
- translations/ui-orders/pl.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
> Update translation strings as of 20200930T202600

- translations/ui-orders/ar.json
- translations/ui-orders/fr_FR.json
> Update translation strings as of 20201005T202004

- CHANGELOG.md
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POInvoices/POInvoicesContainer.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/components/PurchaseOrder/Summary/TotalExpendedValue/TotalExpendedValue.js
- src/components/PurchaseOrder/Summary/TotalExpendedValue/index.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-487 …
> UIOR-487 Display "Total expended" in PO summary

- translations/ui-orders/ar.json
- translations/ui-orders/ca.json
- translations/ui-orders/da.json
- translations/ui-orders/de.json
- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/fr.json
- translations/ui-orders/fr_FR.json
- translations/ui-orders/he.json
- translations/ui-orders/hi_IN.json
- translations/ui-orders/hu.json
- translations/ui-orders/it_IT.json
- translations/ui-orders/ja.json
- translations/ui-orders/ko.json
- translations/ui-orders/pl.json
- translations/ui-orders/pt_BR.json
- translations/ui-orders/pt_PT.json
- translations/ui-orders/ru.json
- translations/ui-orders/ur.json
- translations/ui-orders/zh_CN.json
- translations/ui-orders/zh_TW.json
> Update translation strings as of 20201008T220807

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrderLinesListContainer.js
- src/OrderLinesList/utils.js
- translations/ui-orders/en.json
show one more olumn with orders status
https://issues.folio.org/browse/UIOR-620
While it's …
> UIOR-620 show Order workflow for lines list

- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-620 …
> UIOR-620 new label

- translations/ui-orders/de.json
- translations/ui-orders/es.json
- translations/ui-orders/es_419.json
- translations/ui-orders/es_ES.json
- translations/ui-orders/ja.json
> Update translation strings as of 20201102T140138

- translations/ui-orders/en_GB.json
- translations/ui-orders/en_SE.json
- translations/ui-orders/en_US.json
> Update translation strings as of 20201102T163253

- CHANGELOG.md
- src/components/LayerCollection/LayerPO.js
https://issues.folio.org/browse/UIOR-622 …
> UIOR-622 Activate "re-encumber' toggle by default

- translations/ui-orders/ar.json
- translations/ui-orders/ja.json
> Update translation strings as of 20201105T151643

- src/common/resources/configuration.js
- src/components/Utils/resources.js
we don't need to refresh such data, it's static and doesn't depend on updated resources …
> remove some extra API calls

- src/OrdersList/OrdersListContainer.js
missed one place with search by specific index
https://issues.folio.org/browse/UIOR-623 …
> UIOR-623 fix missed search in Orders list

- src/OrdersList/OrdersListContainer.js
https://issues.folio.org/browse/UIOR-623 …
> UIOR-623 missed equal

- CHANGELOG.md
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/PurchaseOrder/PO.js
- src/components/Utils/orderResource.js
- src/components/Utils/resources.js
https://issues.folio.org/browse/UIOR-626
`poNumper` consists of `prefix`+`poNumber`+`suffix`
For cloning order, it requires to fetch the next poNumber from BE and then concatenate it with existing prefix and suffix …
> UIOR-626 Clone PO does not clone Prefix and Suffix

- CHANGELOG.md
- package.json
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/POLine/Location/LocationForm.js
revert UIOR-609 changes - it will be handled later within corresponding back-end changes
https://issues.folio.org/browse/UIOR-609 …
> UIOR-609 revert - disable field location of order is not pending

- CHANGELOG.md
- package.json
- src/components/POLine/POLineAgreementLines/POLineAgreementLines.js
- src/components/POLine/POLineAgreementLines/POLineAgreementLines.test.js
- src/components/POLine/POLineAgreementLines/POLineAgreementLinesContainer.js
- src/components/Utils/api.js
Fetch agreements after agreement lines to display statuses
https://issues.folio.org/browse/UIOR-627 …
> UIOR-627 add agreement fetching for statuses

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-630 …
> Release v2.2.4

- src/components/POLine/POLineAgreementLines/POLineAgreementLinesContainer.js
https://github.com/folio-org/ui-orders/pull/1006#pullrequestreview-533413169
While it's …
> UIOR-627-fix-review-comment

- CHANGELOG.md
- package.json
- src/components/POLine/POLineAgreementLines/POLineAgreementLinesContainer.js
- src/components/POLine/POLineAgreementLines/fetchAgreementLines.js
To support back-end queries for ERM api we have to pass `||` instead of `or` for regular folio back-ends.
https://issues.folio.org/browse/UIOR-627 …
> UIOR-627-fix-more-than-one-related-agreement

- CHANGELOG.md
- package.json
- src/components/POLine/POLineAgreementLines/fetchAgreementLines.js
wrong format for ERM back-end
While it's helpful for reviewers to help identify potential …
> UIOR-627-next-fix-1

- package.json
> Bump invoice interface

- CHANGELOG.md
- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
https://issues.folio.org/browse/UIOR-629 …
> UIOR-629 Remove accessProvider field requirement

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md.txt
Add personal data disclosure form
https://issues.folio.org/browse/UIOR-639
While it's …
> UIOR-639 Add personal data disclosure form

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
Order not loading when system cannot get exchange rate for chosen currency
https://issues.folio.org/browse/UIOR-642
fetch PO with the list query API …
> UIOR-642 fetch order as list to avoid error

- package.json
- src/components/POLine/POLineForm.js
- test/bigtest/tests/line-edit-test.js
- test/bigtest/tests/orders-test.js
> fix tests and warnings

- package.json
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListActionMenu.js
- src/common/ExportSettingsModal/ExportSettingsModal.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-638?focusedCommentId=95620&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-95620
- add `ExportSettingsModal` for orders;
- add message to `ExportSettingsModal`; …
> UIOR-638 Add export settings modal for orders

- .eslintrc
- CHANGELOG.md
- test/bigtest/.eslintrc
https://issues.folio.org/browse/UIOR-650 …
> UIOR-650 revert react, use common eslint config

- CHANGELOG.md
- src/components/Utils/orderResource.js
https://issues.folio.org/browse/UIOR-647 …
> UIOR-647 remove statuses on cloned po line

- src/common/ExportSettingsModal/ExportSettingsModalContainer.js
https://issues.folio.org/browse/UIOR-645
- create the file name based on the Date and time of export: `order-export-yyyy-mm-dd-hh:mm` …
> UIOR-645 - add file name to order export

- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/PO.js
https://sonarcloud.io/project/issues?id=org.folio%3Aui-orders&resolved=false&types=BUG
While …
> fix sonarcloud bugs

- CHANGELOG.md
- src/OrderLinesList/OrderLinesFilters.js
- src/OrderLinesList/constants.js
- src/OrderLinesList/utils.js
https://issues.folio.org/browse/UIOR-654 …
> UIOR-654 Filter order lines by acquisition units

- src/OrderLinesList/OrderLinesFilters.js
https://issues.folio.org/browse/UIOR-654 …
> UIOR-654 move acqunit filter above

- src/components/POLine/Cost/CostView.js
- src/components/POLine/Cost/ExchangeRateValue/ExchangeRateValue.js
- src/components/POLine/Cost/ExchangeRateValue/index.js
https://issues.folio.org/browse/UIOR-610?focusedCommentId=97161&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-97161 …
> UIOR-610 Add Exchange rate to POL details

- CHANGELOG.md
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListContainer.js
- src/OrdersList/OrdersListSearchConfig.js
- src/OrdersList/useBuildQuery.js
- src/OrdersList/useSearchableIndexes.js
https://issues.folio.org/browse/UISACQCOMP-16 …
> UISACQCOMP-16 fix orders date search format

- src/components/POLine/Cost/CostForm.js
- translations/ui-orders/en.json
use common code for validation
https://issues.folio.org/browse/UIF-280 …
> UIF-280 remove code from ui-orders

- CHANGELOG.md
- src/OrderLinesList/utils.js
- src/OrdersList/useBuildQuery.js
https://issues.folio.org/browse/UIOR-648 …
> UIOR-648 default sorting by updatedDate

- package.json
- src/OrdersList/OrdersListFilterConfig.js
> revert a typo change, orders constants still there

- package.json
https://issues.folio.org/browse/UIOR-656 …
> UIOR-656 Update stripes-cli to v2

- package.json
> bump erm interface

- CHANGELOG.md
- src/common/POFields/OngoingInfoFields/FieldRenewalDate.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-659 …
> UIOR-659 Cannot save template with renewal date

- CHANGELOG.md
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/Utils/resources.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
https://issues.folio.org/browse/UIOR-660 …
> UIOR-660 fix refresh tempaltes list

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-662 …
> UIOR-662 Update view for Vendor reference number

- CHANGELOG.md
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/components/PurchaseOrder/Summary/TotalEncumberedValue/TotalEncumberedValue.js
- src/components/PurchaseOrder/Summary/TotalExpendedValue/TotalExpendedValue.js
https://issues.folio.org/browse/UIOR-658 …
> UIOR-658 refactor totalExpended totalEncumbered

- CHANGELOG.md
- src/OrderLinesList/OrdersLinesSearchConfig.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-668 …
> UIOR-668 Vendor ref number search is not working

- CHANGELOG.md
- src/components/Utils/orderResource.js
https://issues.folio.org/browse/UIOR-698 …
> UIOR-698 Duplicate PO is created as "Approved"

- package.json
https://issues.folio.org/browse/UIOR-699 …
> UIOR-699 missed permission

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-700 …
> UIOR-700 Orders: Create - orders user can't view

- Jenkinsfile
- package.json
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLine.js
- src/components/PurchaseOrder/PO.js
https://issues.folio.org/browse/UIOR-697 …
> UIOR-697 compile tranlsations

- CHANGELOG.md
- package.json
- src/OrdersList/OrdersListFilters.js
- src/OrdersList/constants.js
- test/bigtest/tests/PurchaseOrder/close-order-modal-test.js
- test/bigtest/tests/PurchaseOrder/order-approve-is-not-required-test.js
https://issues.folio.org/browse/UIOR-710 …
> UIOR-710 Filter order by subscription = yes/no

- src/PrintOrder/PrintContent/PrintContent.js
- test/bigtest/network/config.js
- test/bigtest/tests/PurchaseOrder/clone-order-test.js
- test/bigtest/tests/PurchaseOrder/delete-line-test.js
- test/bigtest/tests/PurchaseOrder/delete-order-test.js
- test/bigtest/tests/PurchaseOrder/order-approve-is-required-test.js
- test/bigtest/tests/PurchaseOrder/unopen-order-test.js
> UIOR-674 remove extra sheet

- src/OrdersList/OrdersListFilters.js
- translations/ui-orders/en.json
Update filter label to match PO field label
https://issues.folio.org/browse/UIOR-714
While …
> UIOR-714 fix label for manual renewal

- src/OrdersList/OrdersListFilters.js
- translations/ui-orders/en.json
Update "Renewal Review period" filter label to match PO field label
https://issues.folio.org/browse/UIOR-715 …
> UIOR-715 fix labels to use the same as details

- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
Support new error codes of Order validation on UI
https://issues.folio.org/browse/UIOR-711 …
> UIOR-711 new error codes

- src/OrdersList/OrdersListFilters.js
https://issues.folio.org/browse/UIOR-715 …
> UIOR-715 fix wrong message label

- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PO.test.js
- src/components/PurchaseOrder/getPOActionMenu.js
orders - Acquisition units not restrict edit create or delete actions from action menu
https://issues.folio.org/browse/UIOR-686 …
> UIOR-686 check acq units for order and po line actions

- src/components/POLine/LineLinkedInstances/useLinkedInstances.js
- src/components/POLine/LineLinkedInstances/useLinkedInstances.test.js
https://issues.folio.org/browse/UIOR-690 …
> UIOR-690 use titles to fetch linked instances

- CHANGELOG.md
- src/components/POLine/POLineView.js
https://issues.folio.org/browse/UIOR-661
single Pane prop, covered by old bigtest tests …
> UIOR-661 Keep Title visible on POL when scrolling down the page

- CHANGELOG.md
- src/OrdersList/OrdersList.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
- src/index.js
https://issues.folio.org/browse/UIOR-677 …
> UIOR-677 Apply baseline keyboard shortcuts

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- src/components/Utils/getOrderTemplateValue.js
- src/components/Utils/getOrderTemplateValue.test.js
https://issues.folio.org/browse/UIOR-720 …
> UIOR-720 Possible to save POL with no location even when location is required

- src/PrintOrder/ComponentToPrint/ComponentToPrint.js
- src/PrintOrder/ComponentToPrint/PrintOrderLines/PrintOrderLines.css
- src/PrintOrder/ComponentToPrint/PrintOrderLines/PrintOrderLines.test.js
- src/PrintOrder/ComponentToPrint/PrintOrderLines/utils.js
- src/PrintOrder/PrintContent/PrintContent.css
- src/PrintOrder/PrintOrder.js
- src/PrintOrder/hydrateOrderToPrint.js
- src/common/ExportSettingsModal/utils/createExportReport.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- test/bigtest/tests/create-order-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-721 …
> UIOR-721 improve print order UX and styles

- src/OrdersList/OrdersList.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/POForm.js
- src/index.js
> use common handleKeyCommand

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-723 …
> UIOR-723 Multiple PO lines created when 'Save & Open' used on POL with fund distribution and no budget

- CHANGELOG.md
- src/common/POLFields/FieldsLocation/FieldsLocation.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/POLineForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-726 …
> UIOR-726 Restrict editing order location and quantity on POL

- CHANGELOG.md
- src/common/ExportSettingsModal/utils/createExportReport.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-739 …
> UIOR-739 Order export to CSV does not perform when attempting export of 50+ records

- src/OrdersList/OrderExportSettingsModalContainer.js
- src/OrdersList/constants.js
https://issues.folio.org/browse/UIOR-739 …
> UIOR-739 fix orders export on Orders screen

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- test/bigtest/tests/add-Line-button-for-closed-orders-test.js
- test/bigtest/tests/add-line-test.js
https://issues.folio.org/browse/UIOR-742 …
> UIOR-742 Fix sorting by Title

- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
> UIOR-737- fix labels

- src/components/POLine/Eresources/EresourcesView.js
https://issues.folio.org/browse/UIOR-758 …
> UIOR-758 Error message when view order templates without eresource

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/const.js
- src/components/Utils/Validate.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-751 …
> Publication date not populated when using 'Title look up'

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-765 …
> UIOR-765 Support erm 5.0 interface

- CHANGELOG.md
- src/PrintOrder/PrintContent/PrintContent.css
- src/PrintOrder/PrintOrder.js
- src/PrintOrder/utils.js
https://issues.folio.org/browse/UIOR-775 …
> UIOR-775 global CSS styles force landscape printing in other modules

- CHANGELOG.md
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostView.js
- src/components/POLine/Cost/RolloverAdjustmentAmount/RolloverAdjustmentAmount.js
- src/components/POLine/Cost/RolloverAdjustmentAmount/index.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-768 …
> UIOR-768 Fiscal year rollover amount not shown on POL after rollover

- src/components/POLine/LineLinkedInstances/LineLinkedInstances.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateTagsView/OrderTemplateTagsView.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.test.js
- src/settings/OrderTemplates/OrderTemplateView/TemplateInformationView/TemplateInformationView.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineLocationsForm/POLineLocationsForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/POLineOtherResourcesForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/POLinePhysicalForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/POLineVendorForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderNotesForm/PurchaseOrderNotesForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderSummaryForm/PurchaseOrderSummaryForm.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/TemplateInformationForm.test.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.test.js
https://issues.folio.org/browse/FAT-36 …
>  FAT-36 UI tests replacement with RTL/Jest

- CHANGELOG.md
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-776 …
> UIOR-776 Display 'Date Ordered' on PO

- CHANGELOG.md
- package.json
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-551 …
> UIOR-551 Add translations for permissions

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-789 …
> UIOR-789 UIOR (ui-orders) R2 Hotfix #2 release

- CHANGELOG.md
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersList.test.js
- src/OrdersList/OrdersListContainer.js
- src/OrdersList/OrdersListContainer.test.js
- src/OrdersList/hooks/index.js
- src/OrdersList/hooks/useBuildQuery/index.js
- src/OrdersList/hooks/useBuildQuery/useBuildQuery.js
- src/OrdersList/hooks/useBuildQuery/useBuildQuery.test.js
- src/OrdersList/hooks/useOrders/index.js
- src/OrdersList/hooks/useOrders/useOrders.js
- src/OrdersList/hooks/useSearchableIndexes/index.js
- src/OrdersList/hooks/useSearchableIndexes/useSearchableIndexes.js
- src/OrdersList/hooks/useSearchableIndexes/useSearchableIndexes.test.js
- test/bigtest/network/factories/agreement-line.js
- test/bigtest/network/factories/contributor-name-type.js
- test/bigtest/network/factories/identifier-type.js
- test/bigtest/network/factories/invoice-line.js
- test/bigtest/network/factories/invoice.js
- test/bigtest/network/factories/note-type.js
- test/bigtest/network/factories/note.js
- test/bigtest/network/factories/orderInvoiceRelationships.js
- test/bigtest/network/factories/orderTemplate.js
- test/bigtest/network/factories/prefix.js
- test/bigtest/network/factories/receivingHistory.js
- test/bigtest/network/factories/suffix.js
https://issues.folio.org/browse/UIOR-782
cover by tests (hook) …
> UIOR-782 Order Tab - Implement MCL Next/Previous pagination

- src/OrdersList/hooks/useOrders/useOrders.js
- src/OrdersList/hooks/useOrders/useOrders.test.js
https://issues.folio.org/browse/UIOR-782 …
> UIOR-782 orders pagination tests

- CHANGELOG.md
- src/common/POLFields/FieldsLocation/FieldsLocation.js
https://issues.folio.org/browse/UIOR-781 …
> UIOR-781 Location (holding) field adjustments for None or Instance Create inventory setting

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrderLinesList.test.js
- src/OrderLinesList/OrderLinesListContainer.js
- src/OrderLinesList/OrderLinesListContainer.test.js
- src/OrderLinesList/hooks/index.js
- src/OrderLinesList/hooks/useLinesQuery/index.js
- src/OrderLinesList/hooks/useLinesQuery/useLinesQuery.js
- src/OrderLinesList/hooks/useLinesQuery/useLinesQuery.test.js
- src/OrderLinesList/hooks/useNormalizedISBN/index.js
- src/OrderLinesList/hooks/useNormalizedISBN/useNormalizedISBN.js
- src/OrderLinesList/hooks/useNormalizedISBN/useNormalizedISBN.test.js
- src/OrderLinesList/hooks/useOrderLines/index.js
- src/OrderLinesList/hooks/useOrderLines/useOrderLines.js
- src/OrderLinesList/hooks/useOrderLines/useOrderLines.test.js
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersListContainer.js
- src/OrdersList/hooks/useOrders/useOrders.js
https://issues.folio.org/browse/UIOR-783 …
> UIOR-783 Order lines Tab - Implement MCL Next/Previous pagination

- CHANGELOG.md
- src/settings/ClosingReasons/ClosingReasons.js
- src/settings/ClosingReasons/ClosingReasons.test.js
https://issues.folio.org/browse/UIOR-797 …
> UIOR-797 "New" button active for user without permission to edit reason for closure in settings

- CHANGELOG.md
- src/OrdersList/OrdersListFilters.js
- src/OrdersList/OrdersListFilters.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-802 …
> UIOR-802 Filter label contains extra 's'

- CHANGELOG.md
- src/index.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.test.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.js
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.test.js
https://issues.folio.org/browse/UIOR-801 …
> UIOR-801 Settings (Order templates) | Apply baseline keyboard shortcuts

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-825 …
> UIOR-825 Add constraint for POL: physical POL should contain only Physical element and electronic only Eresource

- src/OrderLinesList/utils.js
https://issues.folio.org/browse/UIOR-830 …
> UIOR-830 update search query by product id

- CHANGELOG.md
- src/components/POLine/LineLinkedInstances/LineLinkedInstances.js
- src/components/POLine/LineLinkedInstances/LineLinkedInstances.test.js
- src/components/POLine/LineLinkedInstances/hooks/useLinkedInstances/useLinkedInstances.js
- src/components/POLine/LineLinkedInstances/hooks/useLinkedInstances/useLinkedInstances.test.js
https://issues.folio.org/browse/UIOR-833 …
> UIOR-833 Allow user to select instance for Title AND edit title from POL view

- src/components/POLine/LineLinkedInstances/hooks/useLinkedInstances/useLinkedInstances.js
- translations/ui-orders/ko.json
https://issues.folio.org/browse/UIOR-832
- display linked titles in alphabetic order instead of displaying unique instances …
> UIOR-832 Display titles instance

- src/components/POLine/LineLinkedInstances/LineLinkedInstances.js
https://issues.folio.org/browse/UIOR-831 …
> UIOR-831 Open accordion for package line by default

- CHANGELOG.md
- src/components/PurchaseOrder/PO.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-808 …
> UIOR-808 Intercept user with confirmation when user unopens Order

- CHANGELOG.md
- src/common/POFields/FieldIsApproved.js
- src/common/POFields/OngoingInfoFields/FieldIsManualRenewal.js
- src/common/POFields/OngoingInfoFields/FieldRenewalSubscription.js
- src/common/POLFields/EresourcesFields/FieldAccessProvider.js
- src/common/POLFields/PhysicalFields/FieldMaterialSupplier.js
- src/common/VisibilityControl/VisibilityControl.css
- src/common/VisibilityControl/VisibilityControl.js
- src/common/VisibilityControl/index.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/PackagePoLineField/PackagePoLineField.css
- src/components/POLine/Item/PackagePoLineField/PackagePoLineField.js
- src/components/PurchaseOrder/OngoingOgderInfo/OngoingInfoForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineEresourcesForm/POLineEresourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineOtherResourcesForm/POLineOtherResourcesForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLinePhysicalForm/POLinePhysicalForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineVendorForm/POLineVendorForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderSummaryForm/PurchaseOrderSummaryForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/FieldHideAll/FieldHideAll.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/FieldHideAll/index.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/TemplateInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/TemplateInformationForm/TemplateInformationForm.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-848 …
> UIOR-848 Allow user to indicate in order template that specific fields should be hidden on order form

- CHANGELOG.md
- src/common/POLFields/DetailsFields/FieldCheckInItems.js
https://issues.folio.org/browse/UIOR-862 …
> UIOR-862 Order template is not saved without receiving workflow

- CHANGELOG.md
- src/common/IfFieldVisible/IfFieldVisible.js
- src/common/IfFieldVisible/IfFieldVisible.test.js
- src/common/IfFieldVisible/index.js
- src/common/IfVisible/IfVisible.js
- src/common/IfVisible/IfVisible.test.js
- src/common/IfVisible/index.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Eresources/EresourcesForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Other/OtherForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Physical/PhysicalForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/PurchaseOrder/OngoingOgderInfo/OngoingInfoForm.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
https://issues.folio.org/browse/UIOR-850 …
> UIOR-850 Hide all fields in PO or POL that are set to hide in order template

- CHANGELOG.md
- package.json
- src/settings/AcquisitionMethods/AcquisitionMethods.js
- src/settings/AcquisitionMethods/AcquisitionMethods.test.js
- src/settings/AcquisitionMethods/index.js
- src/settings/OrdersSettings.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-846 …
> UIOR-846 Create area Settings->Orders->Acquisition methods

- src/components/POLine/Cost/CostForm.css
- src/components/POLine/Cost/CostForm.js
https://issues.folio.org/browse/UIOR-848 …
> UIOR-848 fix cost form styles

- src/components/POLine/Cost/CostForm.js
https://issues.folio.org/browse/UIOR-850 …
> UIOR-850 wrap cost fields

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
https://issues.folio.org/browse/UIOR-863 …
> UIOR-863 POL Title selection overwriting Order template location

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-849 …
> UIOR-849 Allow user to show all hidden fields from PO or POL

- CHANGELOG.md
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemForm.test.js
- src/components/POLine/POLineForm.js
https://issues.folio.org/browse/UIOR-854 …
> UIOR-854 Order template not populating Holdings correctly

- package.json
- src/components/POLine/POLineForm.js
- src/components/PurchaseOrder/POForm.js
- translations/ui-orders/en.json
> UIOR-849 add missed permission to control 'Show hidden' toggle

- CHANGELOG.md
- src/common/hooks/useAcqMethods/useAcqMethods.js
- src/common/hooks/useAcqMethods/useAcqMethods.test.js
- src/settings/AcquisitionMethods/AcquisitionMethods.js
- test/bigtest/network/serializers/acquisitionMethod.js
https://issues.folio.org/browse/UIOR-872 …
> UIOR-872 Rename collection field name for Acquisition method

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineForm.test.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/POForm.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-871 …
> UIOR-871 Move 'show all hidden fields' for PO or POL to Actions menu

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-875 …
> UIOR-875 v3.0.3 bugfix release

- CHANGELOG.md
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/POForm.test.js
- test/bigtest/tests/edit-order-test.js
https://issues.folio.org/browse/UIOR-869 …
> UIOR-869 Do not show ongoing order accordion for One-time orders

- CHANGELOG.md
- src/OrderLinesList/Details/OrderLineDetails.js
- src/OrderLinesList/Details/OrderLineDetails.test.js
- src/common/IfFieldVisible/IfFieldVisible.test.js
- src/common/hooks/index.js
- src/common/hooks/useOrderTemplate/index.js
- src/common/hooks/useOrderTemplate/useOrderTemplate.js
- src/common/hooks/useOrderTemplate/useOrderTemplate.test.js
- src/components/POLine/Cost/CostView.js
- src/components/POLine/Eresources/EresourcesView.js
- src/components/POLine/Item/ItemView.js
- src/components/POLine/Other/OtherView.js
- src/components/POLine/POLine.js
- src/components/POLine/POLine.test.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineView.js
- src/components/POLine/Physical/PhysicalView.js
- src/components/POLine/Vendor/VendorView.js
- src/components/PurchaseOrder/OngoingOgderInfo/OngoingOrderInfoView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PO.test.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-855
https://issues.folio.org/browse/UIOR-856
While it's …
> UIOR-855 Allow user to show all hidden fields

- CHANGELOG.md
- src/common/DuplicateLinesModal/DuplicateLinesList/DuplicateLinesList.js
- src/common/DuplicateLinesModal/DuplicateLinesList/DuplicateLinesList.test.js
- src/common/DuplicateLinesModal/DuplicateLinesList/index.js
- src/common/DuplicateLinesModal/DuplicateLinesModal.js
- src/common/DuplicateLinesModal/DuplicateLinesModal.test.js
- src/common/DuplicateLinesModal/index.js
- src/common/constants/constants.js
- src/common/utils/index.js
- src/common/utils/validateDuplicateLines.js
- src/common/utils/validateDuplicateLines.test.js
- src/components/LayerCollection/LayerPOLine.js
- test/bigtest/tests/POLine/line-create-test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-864 …
> UIOR-864 Check for potential duplicate order lines

- CHANGELOG.md
- src/components/Utils/getIdentifierTypesForSelect.js
https://issues.folio.org/browse/UIOR-843 …
> UIOR-843 Add two additional "Resource identifier" types to the product id type selection for POL

- CHANGELOG.md
- package.json
- src/common/POLFields/DetailsFields/FieldAcquisitionMethod.js
- src/common/POLFields/DetailsFields/FieldAutomaticExport.js
- src/common/POLFields/DetailsFields/FieldAutomaticExport.test.js
- src/common/POLFields/VendorFields/FieldVendorAccountNumber.js
- src/common/POLFields/index.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/Vendor/VendorForm.js
- src/components/Utils/toggleAutomaticExport.js
- src/components/Utils/toggleAutomaticExport.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/POLineDetailsForm/POLineDetailsForm.js
- test/jest/fixtures/index.js
- test/jest/fixtures/integrationConfig.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-371 …
> UIOR-371 Allow user to set Acq method EDIFACT export triggers for POL

- CHANGELOG.md
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-883 …
> UIOR-883 Translations filter by export date

- CHANGELOG.md
- src/common/hooks/index.js
- src/common/hooks/useOpenOrderSettings/index.js
- src/common/hooks/useOpenOrderSettings/useOpenOrderSettings.js
- src/common/hooks/useOpenOrderSettings/useOpenOrderSettings.test.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- src/settings/OpenOrder/OpenOrderForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-888 …
> UIOR-888 Disable Check for potential duplicate order lines in Settings

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- src/common/DuplicateLinesModal/DuplicateLinesList/DuplicateLinesList.js
- src/components/POLine/POLineDetails/POLineDetails.js
https://issues.folio.org/browse/UIOR-910 …
> UIOR-910 Adding tenant's timezone in UI

- CHANGELOG.md
- src/settings/OrderTemplates/OrderTemplatesList/OrderTemplatesList.js
- src/settings/POLinesLimitForm.js
https://issues.folio.org/browse/UIOR-897 …
> UIOR-897 Settings > Orders > change focus

- CHANGELOG.md
- src/PrintOrder/ComponentToPrint/ComponentToPrint.js
- src/PrintOrder/ComponentToPrint/PrintOrderLines/utils.js
- src/PrintOrder/utils.js
https://issues.folio.org/browse/UIOR-909 …
> UIOR-909 Only printing part of the primary address for orders

- src/components/LayerCollection/LayerPOLine.js
- src/components/PurchaseOrder/PO.js
https://issues.folio.org/browse/UIOR-903 …
> UIOR-903 Manual PO condition

- CHANGELOG.md
- src/OrderLinesList/hooks/useOrderLines/useOrderLines.js
https://issues.folio.org/browse/UIOR-913 …
> UIOR-913 Search by product id ISBN is not working while adding invoice line based on POL

- CHANGELOG.md
- src/components/Utils/orderResource.js
https://issues.folio.org/browse/UIOR-914 …
> UIOR-914 Exported date not removed when order is duplicated

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-918 …
> UIOR-918 Replace deprecated permission search.instances.facets.collection.get

- CHANGELOG.md
- src/common/ExportSettingsModal/utils/createExportReport.js
- src/common/ExportSettingsModal/utils/createExportReport.test.js
- src/common/ExportSettingsModal/utils/exportManifest.js
- src/common/ExportSettingsModal/utils/getExportData.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
https://issues.folio.org/browse/UIOR-921 …
> UIOR-921 Orders csv export has errors in the location column when orders are linked to holdings

- CHANGELOG.md
- src/common/ExportSettingsModal/ExportSettingsModalContainer.js
https://issues.folio.org/browse/UIOR-922 …
> UIOR-922 exportCsv is deprecated in stripes-utils

- src/common/ExportSettingsModal/utils/getExportData.js
https://issues.folio.org/browse/UIOR-921 …
> UIOR-921 Fix locationIds

- CHANGELOG.md
- src/components/Utils/order/showUpdateOrderError.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-919 …
> UIOR-919 Order: Error message does not indicate what Fund does not have money

- CHANGELOG.md
- src/common/utils/validateDuplicateLines.js
- src/common/utils/validateDuplicateLines.test.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/Utils/api.js
- src/components/Utils/resources.js
https://issues.folio.org/browse/UIOR-929 …
> UIOR-929 Order duplicate verification is NOT made when saving PO line

- CHANGELOG.md
- package.json
> UIOR-930 Release v3.1.1

- CHANGELOG.md
- package.json
- src/index.js
https://issues.folio.org/browse/UIOR-932 …
> UIOR-932 Remove react-hot-loader - unmaintained, security (CVE-2021-44906)

- src/PrintOrder/ComponentToPrint/ComponentToPrint.js
- src/PrintOrder/ComponentToPrint/ComponentToPrint.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-928?focusedCommentId=126569&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-126569 …
> UIOR-928 Update label

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-945 …
> UIOR-945 release v3.1.2

- CHANGELOG.md
- src/common/POFields/OngoingInfoFields/FieldRenewalDate.js
- src/common/POFields/OngoingInfoFields/FieldRenewalInterval.js
https://issues.folio.org/browse/UIOR-961 …
> UIOR-961 Renewal date and interval not required

- CHANGELOG.md
- package.json
- src/components/PurchaseOrder/Summary/SummaryForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-933 …
> UIOR-933 Permission Orders: Approve purchase order

- .eslintrc
- CHANGELOG.md
- package.json
- src/common/ExportSettingsModal/utils/getExportData.js
https://issues.folio.org/browse/UIOR-962 …
> UIOR-962 replace babel-eslint with @babel/eslint-parser

- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- src/common/POLFields/DetailsFields/FieldPaymentStatus.js
- src/common/POLFields/DetailsFields/FieldReceiptStatus.js
- src/components/POLine/utils.js
- src/components/POLine/utils.test.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-740
https://issues.folio.org/browse/UIOR-889
While it's …
> UIOR-740 Add tooltip, fix conditions

- src/OrderLinesList/OrderLinesList.test.js
- src/components/POLine/utils.js
https://issues.folio.org/browse/UIOR-740?focusedCommentId=130000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-130000 …
> UIOR-740 Cancel line icon

- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/constants.js
> UIOR-952 Saving an order template can fail without a visible message

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrdersList/OrdersList.js
- src/PrintOrder/ComponentToPrint/PrintOrderLines/PrintOrderLines.js
- src/common/VisibilityControl/VisibilityControl.js
- src/components/PurchaseOrder/LineListing/LineListing.js
- src/components/PurchaseOrder/Summary/SummaryView.js
https://issues.folio.org/browse/UIOR-969 …
> UIOR-969 ui-orders: module warnings analysis

- CHANGELOG.md
- src/components/POLine/POLineDetails/POLineDetails.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
https://issues.folio.org/browse/UIOR-966 …
> UIOR-966 Add copy icon to PO and POL number

- package.json
https://issues.folio.org/browse/UIOR-893 …
> UIOR-893 missed permission and interface

- CHANGELOG.md
- package.json
- src/common/hooks/index.js
- src/common/hooks/useInstance/index.js
- src/common/hooks/useInstance/useInstance.js
- src/common/hooks/useInstance/useInstance.test.js
- src/components/LayerCollection/LayerPO.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/Item/util.js
- src/components/POLine/Item/util.test.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineForm.test.js
- src/components/PurchaseOrder/POForm.js
- src/components/PurchaseOrder/POForm.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-973
https://issues.folio.org/browse/UIOR-975
While it's …
> UIOR-973 Creating an order from instance record

- CHANGELOG.md
- src/PrintOrder/ComponentToPrint/PrintOrderLines/utils.js
https://issues.folio.org/browse/UIOR-912 …
> UIOR-912 Printing Product IDs on separate lines which makes them hard to read

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-981 …
> UIOR-981 Grant budget permissions

- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-973 …
> UIOR-973 Update pathname after POL creation

- CHANGELOG.md
- package.json
- src/common/constants/api.js
- src/common/hooks/index.js
- src/common/hooks/useTitleMutation/index.js
- src/common/hooks/useTitleMutation/useTitleMutation.js
- src/common/hooks/useTitleMutation/useTitleMutation.test.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/POLineForm.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-745
Title update will be removed from UI after BE is implemented (and code smell will go away) …
> UIOR-745 set Must acknowledge receiving note

- src/OrderLinesList/Details/OrderLineDetails.js
- src/components/POLine/ChangeInstanceConnection/hooks/useChangeInstanceConnection/useChangeInstanceConnection.js
- src/components/POLine/POLine.js
- src/components/POLine/POLineView.js
https://issues.folio.org/browse/UIOR-979
Refetch details pane after instance changing.
While …
> UIOR-979 Instance connection of POL (integration with back end): refetch

- CHANGELOG.md
- package.json
- src/common/constants/routes.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/getPOActionMenu.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-985 …
> UIOR-985 Add 'New invoice' action for PO actions menu

- CHANGELOG.md
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-990 …
> UIOR-990 New invoice action (PO details)

- CHANGELOG.md
- src/common/constants/errorCodes.js
- src/components/LayerCollection/LayerPOLine.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-994 …
> UIOR-994 Error handling improvement

- src/common/constants/errorCodes.js
- src/components/LayerCollection/LayerPOLine.js
- translations/ui-orders/en.json
> UIOR-994 add new error code

- CHANGELOG.md
- src/common/constants/routes.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/getPOActionMenu.js
- translations/ui-orders/en.json
> Merge implemented features from Nolana

- CHANGELOG.md
- package.json
- src/PrintOrder/utils.test.js
- src/common/constants/api.js
- src/common/hooks/index.js
- src/common/hooks/useFundDistributionValidation/index.js
- src/common/hooks/useFundDistributionValidation/useFundDistributionValidation.js
- src/common/hooks/useFundDistributionValidation/useFundDistributionValidation.test.js
- src/components/LayerCollection/LayerPOLine.js
- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://issues.folio.org/browse/UIOR-978 …
> UIOR-978 100% of total calculation is different on FE and BE

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
https://issues.folio.org/browse/UIOR-1000 …
> UIOR-1000 Unable to select account number

- CHANGELOG.md
- src/components/PurchaseOrder/PO.test.js
- src/components/PurchaseOrder/getPOActionMenu.js
https://issues.folio.org/browse/UIOR-998 …
> UIOR-998 Add icon for Unopen/Reopen

- CHANGELOG.md
- src/settings/OrdersSettings.js
https://issues.folio.org/browse/UIOR-1004 …
> UIOR-1004 Orders (settings): View all settings not allowing user to see Instance matching area

- src/common/hooks/useHandleOrderUpdateError/useHandleOrderUpdateError.test.js
https://issues.folio.org/browse/UIOR-997 …
> UIOR-997 Fix tests

- CHANGELOG.md
- src/components/POLine/LineLinkedInstances/hooks/useLinkedInstances/useLinkedInstances.js
https://issues.folio.org/browse/UIOR-1027
Fix the query for linked titles batch fetch in `useLinkedInstances` hook. …
> UIOR-1027 Linked package titles MCL is showing blank rows

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1032
Update permission sets …
> UIOR-1032 A user with certain permission gets 403 error when viewing order/order line

- .github/workflows/build-npm-release.yml
> UIOR-1031 fix release pipeline

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1042 …
> UIOR-1042 loose plugin dependencies permit incompatible versions

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/index.js
https://issues.folio.org/browse/UIOR-1048
Provide `resetFilters` state on location change to use hook for reset active filters …
> UIOR-1048 No results found shown after return to search page

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1051 …
> Release v3.3.2

- CHANGELOG.md
- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1049 …
> UIOR-1049 Show specified error message when changing of fund distribution for PO Line is blocked

- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1049?focusedCommentId=152066&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-152066 …
> UIOR-1049 update error message

- CHANGELOG.md
- src/OrderLinesList/OrderLinesList.js
- src/OrderLinesList/OrderLinesList.test.js
- src/OrdersList/OrdersList.js
- src/OrdersList/OrdersList.test.js
- src/common/hooks/index.js
- src/common/hooks/useIsRowSelected/index.js
- src/common/hooks/useIsRowSelected/useIsRowSelected.js
- src/common/hooks/useIsRowSelected/useIsRowSelected.test.js
https://issues.folio.org/browse/UIOR-1021 …
> UIOR-1021 Results List | Hyperlink one column to improve accessibility

- CHANGELOG.md
- src/common/ExportSettingsModal/utils/createExportReport.js
- src/common/ExportSettingsModal/utils/createExportReport.test.js
https://issues.folio.org/browse/UIOR-1053
The current flow works like this:
```
1. get all POs
2. get all related PO Lines
3. build an export row for each PO Line
```
As a result, information about POs that do not have PO Lines is not included in the export report.
So, the flow should look like this: 
```
1. get all POs
2. get all related PO Lines
3. for each PO:
- if the PO has PO Lines, build an export row for each related PO Line
- otherwise report only information about the order
```
- What other modules will these …
> UIOR-1053 Include purchase orders without purchase order lines in CSV export report

- CHANGELOG.md
- src/common/VersionView/VersionCheckbox/VersionCheckbox.js
- src/common/VersionView/VersionKeyValue/VersionKeyValue.js
- src/components/POLine/POLineVersionView/LocationVersionView/LocationVersionView.js
- src/components/POLine/POLineVersionView/POLineVersionView.js
- src/components/POLine/POLineVersionView/POLineVersionView.test.js
- src/components/POLine/POLineVersionView/PhysicalVersionView/PhysicalVersionView.js
- src/components/POLine/hooks/useSelectedPOLineVersion/useSelectedPOLineVersion.js
- src/components/PurchaseOrder/POVersionView/PODetailsVersionView/PODetailsVersionView.js
- src/components/PurchaseOrder/POVersionView/POVersionView.js
https://issues.folio.org/browse/UIOR-860 …
> UIOR-860 Show in version history record view, which fields have been edited

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1058 …
> UIOR-1058 Support `inventory` interface version `13.0`

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1058
update missed `search` interface
While it's …
> UIOR-1058 Align the module with API breaking change

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1062 …
> UIOR-1062 bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
> Release v4.0.1

- CHANGELOG.md
- src/settings/ClosingReasons/ClosingReasons.js
https://issues.folio.org/browse/UIOR-1090 …
> UIOR-1090 Permissions: Order settings perms do not allow create new reason for closure

- CHANGELOG.md
> Release v4.0.2

- CHANGELOG.md
- src/common/hooks/useOrderTemplate/useOrderTemplate.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateView.test.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.js
- src/settings/OrderTemplates/OrderTemplateView/OrderTemplateViewContainer.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1056
- Add action item in the order template view action menu
- Add shortcut to perform duplicate action
- Use existing `useOrderTemplate` hook to fetch order template and display loading status on the "Edit" page
- Add unit tests
<details open><summary>Preview</summary>
<p>
</p>
</details> 
Ideally all of the PRs …
> UIOR-1056 Add action for duplicate order template

- CHANGELOG.md
- src/common/ExportSettingsModal/ExportSettingsModalContainer.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1089 …
> UIOR-1089 Success toast message is not shown at the start of export

- CHANGELOG.md
- src/common/utils/getLocations.js
- src/common/utils/getMaterialTypes.js
- src/common/utils/getTenantAddresses.js
https://issues.folio.org/browse/UIOR-1101 …
> UIOR-1101 The 'limit' query parameter is not explicitly set to some version history's requests

- CHANGELOG.md
- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
[UIOR-1104](https://issues.folio.org/browse/UIOR-1104) - Support the new error code when opening/closing/unopening/reopening an order: multipleFiscalYears, "Order line fund distributions have active budgets in multiple fiscal years.".
- add `multipleFiscalYears` to errors map
- add localization message for `multipleFiscalYears`
Ideally all of the PRs …
> UIOR-1104 - add new error `multipleFiscalYears` code

- translations/ui-orders/en.json
> UIOR-1104 Support new error code - translation

- src/components/Utils/orderResource.js
> support pol number sequence

- CHANGELOG.md
- src/components/PurchaseOrder/OngoingOrderInfo/OngoingInfoForm.js
- src/components/PurchaseOrder/OngoingOrderInfo/OngoingOrderInfoView.test.js
[UIOR-1102](https://issues.folio.org/browse/UIOR-1102)
- change status check from `isWorkflowStatusPending` to `isWorkflowStatusOpen` …
> feat:UIOR-1102 - allow ongoing order info while workflowStatus is `Open`

- package.json
> cleanup babel dependencies

- CHANGELOG.md
- package.json
- src/components/PurchaseOrder/POInvoices/POInvoices.js
[UIOR-1106](https://issues.folio.org/browse/UIOR-1106)
- add `useLocalPagination` for POs …
> UIOR-1106 add pagination for the PO invoices

- CHANGELOG.md
- package.json
- src/components/POLine/RelatedInvoiceLines/RelatedInvoiceLines.js
- src/components/POLine/RelatedInvoiceLines/useConnectedInvoiceLines.js
- src/components/POLine/RelatedInvoiceLines/useConnectedInvoiceLines.test.js
[UIOR-1024](https://issues.folio.org/browse/UIOR-1024)
- add `useLocalPagination` for integrating frontend pagination …
> UIOR-1024 - add pagination for Related Invoice line - POLines

- src/components/PurchaseOrder/OngoingOrderInfo/OngoingInfoForm.js
https://issues.folio.org/browse/UIOR-1102 …
> UIOR-1102 disable subscription and renewal note for open status

- src/components/PurchaseOrder/POInvoices/useRelatedInvoices.js
[UIOR-1131](https://issues.folio.org/browse/UIOR-1131)
- Update `queryKey` name due to returning wrong 
https://github.com/folio-org/ui-orders/assets/116072773/4e605578-45c1-467f-8c5f-18b884493dee
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIOR-1131: rename queryKey due to conflict with other query function

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- src/common/constants/errorCodes.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1143
Add the error code to the mapping object and add a translation for it. …
> UIOR-1143 Provide a human-readable error message for `encumbrancesForReEncumberNotFound` code

- CHANGELOG.md
- src/common/VersionView/VersionView.js
- src/common/VersionView/VersionView.test.js
- translations/ui-orders/en.json
https://issues.folio.org/browse/UIOR-1136
Display a meaningful message that indicates the absence of versions.
https://github.com/folio-org/ui-orders/assets/88109087/876034fe-3cb8-415d-9ccb-56294bd2dd59 …
> UIOR-1136 Show a message about the missing version in the audit history

- src/components/POLine/RelatedInvoiceLines/RelatedInvoiceLines.js
- src/components/POLine/RelatedInvoiceLines/constants.js
- src/components/PurchaseOrder/POInvoices/POInvoices.js
- src/components/PurchaseOrder/POInvoices/POInvoices.test.js
- src/components/PurchaseOrder/POInvoices/constants.js
- src/components/PurchaseOrder/POInvoices/useRelatedInvoices.js
[UIOR-1131](https://issues.folio.org/browse/UIOR-1131) - refactor the code and remove unwanted columns
- Remove Subscription related columns from PO - Related Invoices
- Add Subscription related columns for PO Line - Related Invoice lines …
> UIOR-1131: remove subscription info from PO

- CHANGELOG.md
- package.json
[UIOR-1154](https://issues.folio.org/browse/UIOR-1154) …
> UIOR-1154 Upgrade `ui-plugin-find-po-line` and `ui-plugin-find-organization` plugins to `5` version

- src/components/POLine/Vendor/VendorForm.js
- translations/ui-orders/en.json
[UIOR-1142](https://issues.folio.org/browse/UIOR-1142) - POL - Display only active account numbers in dropdown list
- add localization for inactive message
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> UIOR-1142: add localizations for inactive status

- CHANGELOG.md
- package.json
> UIOR-1168 Add missed permission to fetch org types in view only mode

- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
https://issues.folio.org/browse/UIOR-1169
Init PR: #1518  …
> UIOR-1169 Increase the game changer timeout to 50ms

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOR-1172 …
> Update the changelog to reflect the v5.0.1 release

- CHANGELOG.md
- translations/ui-orders/en.json
[UIOR-1150](https://issues.folio.org/browse/UIOR-1150) - add donors facet translation
Related PRs:
- https://issues.folio.org/browse/UIPFPOL-65
- https://github.com/folio-org/stripes-acq-components/pull/732 …
> UIOR-1150: add donors facet translation

- CHANGELOG.md
- src/components/POLine/RelatedInvoiceLines/constants.js
https://folio-org.atlassian.net/browse/UIOR-1220 …
> UIOR-1220 Invoice line Subscription fields are not populated correctly

- CHANGELOG.md
- src/common/constants/constants.js
- src/components/Utils/getIdentifierTypesForSelect.js
https://folio-org.atlassian.net/browse/UIOR-1218
https://github.com/folio-org/ui-orders/assets/88109087/10790442-f89f-4c23-ae65-f05dc823df7f …
> UIOR-1218 Add `LCCN` to list of valid Product identifier types

- src/components/POLine/hooks/useIsFundsRestrictedByLocationIds/useIsFundsRestrictedByLocationIds.js
[UIOR-1184](https://folio-org.atlassian.net/browse/UIOR-1184) - fix validation for location-restricted funds
https://github.com/folio-org/ui-orders/assets/116072773/5cffb453-0823-4ce9-a512-63bc5f9a51d1 …
> UIOR-1184: fix validation for location-restricted funds

- CHANGELOG.md
- src/common/ExportSettingsModal/constants.js
- src/common/ExportSettingsModal/utils/createExportReport.js
- test/jest/fixtures/exportReport.js
- test/jest/fixtures/orderLine.js
[UIOR-1208](https://folio-org.atlassian.net/browse/UIOR-1208) - Add order line "Exchange rate" to order csv export …
> UIOR-1208: add exchange rate for Export settings POL

- src/components/POLine/hooks/useIsFundsRestrictedByLocationIds/useIsFundsRestrictedByLocationIds.js
[UIOR-1184](https://folio-org.atlassian.net/browse/UIOR-1184) - improve fund restriction condition due to it was returning
https://github.com/folio-org/ui-orders/assets/116072773/6cf0833a-1752-4f37-955f-df052f219246
https://github.com/folio-org/ui-orders/assets/116072773/5b7b1605-66ac-4c28-9ab2-da5ba74c0efc
Ideally all of the PRs involved in breaking …
> UIOR-1184: update fund restriction condition

- CHANGELOG.md
- package.json
- src/common/constants/api.js
- src/components/POLine/CalculatedExchangeAmount/CalculatedExchangeAmount.js
- src/components/POLine/CalculatedExchangeAmount/CalculatedExchangeAmount.test.js
- src/components/POLine/CalculatedExchangeAmount/index.js
- src/components/POLine/Cost/CostForm.js
- src/components/POLine/Cost/CostForm.test.js
- src/components/POLine/hooks/index.js
- src/components/POLine/hooks/useExchangeCalculation/index.js
- src/components/POLine/hooks/useExchangeCalculation/useExchangeCalculation.js
- src/components/POLine/hooks/useExchangeCalculation/useExchangeCalculation.test.js
- translations/ui-orders/en.json
[UIOR-1241](https://folio-org.atlassian.net/browse/UIOR-1241) - The exchanged calculated total amount is not displayed when POL in foreign currency
https://github.com/folio-org/ui-orders/assets/116072773/70d82211-5a95-4bbc-982b-bad887595e1f …
> UIOR-1241: display calculated exchange rate in foreign currency

- package.json
> Add erm 7.0 interface support

- CHANGELOG.md
- src/components/PurchaseOrder/POForm.test.js
- src/components/PurchaseOrder/Summary/SummaryForm.js
https://folio-org.atlassian.net/browse/UIOR-1250
https://github.com/folio-org/ui-orders/assets/88109087/f527941b-d410-4020-8ae2-32d101a3d059 …
> UIOR-1250 Correctly specify the field name that should be hidden according to the template

- CHANGELOG.md
- package.json
> Release v6.0.3

- CHANGELOG.md
- package.json
- src/components/POLine/POLineView.js
- src/components/POLine/POLineView.test.js
https://folio-org.atlassian.net/browse/UIOR-1109 - add RoutingList component
https://github.com/folio-org/ui-orders/assets/116072773/1a435555-bb5a-413e-81e1-d90cc87a9478 …
> UIOR-1109: add RoutingList component

- CHANGELOG.md
- package.json
Update `CHANGELOG.md` and `package.json` file for `Release v6.0.4` https://github.com/folio-org/ui-orders/releases/tag/v6.0.4 …
> Release v6.0.4

- src/settings/CentralOrdering/CentralOrderingForm.js
https://folio-org.atlassian.net/browse/UIOR-1232
Original PR: #1581
https://github.com/folio-org/ui-orders/assets/36452096/81248f4e-b815-4f0e-b4e6-61d2b9bcabcc
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> UIOR-1232 Disable field for a user with view only permission

- package.json
- src/settings/RoutingListConfiguration/RoutingListConfiguration.js
- src/settings/RoutingListConfiguration/RoutingListConfiguration.test.js
- src/settings/RoutingListConfiguration/RoutingListConfigurationEdit.js
- src/settings/RoutingListConfiguration/RoutingListConfigurationView.js
- src/settings/RoutingListConfiguration/utils.js
- translations/ui-orders/en.json
UIOR-1249f: fix onCancel display confirmation popup and add missing permissions based on QA team's comments 
- [disable `Edit` button](https://folio-org.atlassian.net/browse/UIOR-1249?focusedCommentId=210145)
- [Display Confirmation popup](https://folio-org.atlassian.net/browse/UIOR-1249?focusedCommentId=210137)
- [Add missing permissions](https://folio-org.atlassian.net/browse/UIOR-1249?focusedCommentId=209195)
https://github.com/folio-org/ui-orders/assets/116072773/27aabec8-0f28-4e2a-94f8-ed5ad112101f
- What other modules …
> UIOR-1249f: fix onCancel display confirmation popup and add missing permissions

- src/settings/RoutingListConfiguration/utils.js
- translations/ui-orders/en.json
[UIOR-1249:](https://folio-org.atlassian.net/browse/UIOR-1249) Update validation logic and error message …
> UIOR-1249: Update validation logic and error message

- CHANGELOG.md
- package.json
- src/components/POLine/RoutingList/RoutingListForm/RoutingListForm.js
- src/components/POLine/RoutingList/RoutingListUsers/RoutingListUserItem.js
- src/components/POLine/RoutingList/RoutingListUsers/RoutingListUsers.css
- src/components/POLine/RoutingList/RoutingListUsers/RoutingListUsers.js
- src/components/POLine/RoutingList/RoutingListUsers/constants.js
- src/components/POLine/RoutingList/RoutingListUsers/utils.js
- translations/ui-orders/en.json
[UIOR-1112:](https://folio-org.atlassian.net/browse/UIOR-1112) Prioritize users in a routing list by drag and drop list
https://github.com/folio-org/ui-orders/assets/116072773/e0b8f83e-4446-45bd-98b7-afad39ae88f8 …
> UIOR-1112: Prioritize users in a routing list by drag and drop list

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1240
Here we updated translation keys by using `stripes-components.saveAndClose ` instead of local key
> UIOR-1240: Use Save & close button label stripes-component translation key 

- CHANGELOG.md
- src/common/constants/constants.js
- src/components/POLine/utils.js
https://folio-org.atlassian.net/browse/UISACQCOMP-193 …
> UISACQCOMP-193 Remove searchLocationIds[] field from PO line Version history

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIOR-1277 …
> UIOR-1277 Bump up  interface

- CHANGELOG.md
- src/common/AddressFilter/AddressFilter.test.js
- src/common/ClosingReasonFilter/ClosingReasonFilter.test.js
- src/common/ExportSettingsModal/ExportSettingsModal.test.js
- src/components/PurchaseOrder/POForm.test.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1289 …
> UIOR-1289 Fix grammar and spelling errors on Settings > Orders > Instance

- src/OrdersList/OrdersListFilters.test.js
- src/components/POLine/Item/ItemView.test.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.test.js
- src/components/PurchaseOrder/PODetails/PODetailsView.test.js
- src/settings/OrderTemplates/OrderTemplatesEditor/PurchaseOrderInformationForm/PurchaseOrderInformationForm.test.js
> UIOR-1289 fix tests

- CHANGELOG.md
- src/common/hooks/consortium/index.js
- src/common/hooks/consortium/useConsortiumPOLineRelatedItems/index.js
- src/common/hooks/consortium/useConsortiumPOLineRelatedItems/useConsortiumPOLineRelatedItems.js
- src/common/hooks/consortium/useConsortiumPOLineRelatedItems/useConsortiumPOLineRelatedItems.test.js
- src/common/hooks/index.js
- src/components/POLine/ChangeInstanceConnection/ChangeInstanceModal/ChangeInstanceModal.js
- src/components/POLine/ChangeInstanceConnection/ChangeInstanceModal/ChangeInstanceModal.test.js
- src/components/POLine/ChangeInstanceConnection/ChangeInstanceModal/ChangeInstanceModalContainer.test.js
- src/components/POLine/ChangeInstanceConnection/ConsortiumRelatedItemsList/ConsortiumRelatedItemsList.js
- src/components/POLine/ChangeInstanceConnection/ConsortiumRelatedItemsList/ConsortiumRelatedItemsList.test.js
- src/components/POLine/ChangeInstanceConnection/ConsortiumRelatedItemsList/index.js
- src/components/POLine/ChangeInstanceConnection/NotMovedItemsModal/NotMovedItemsModal.js
- src/components/POLine/ChangeInstanceConnection/RelatedItemsList/RelatedItemsList.js
- src/components/POLine/ChangeInstanceConnection/RelatedItemsList/RelatedItemsList.test.js
- src/components/POLine/ChangeInstanceConnection/constants.js
- src/components/POLine/ChangeInstanceConnection/hooks/index.js
- src/components/POLine/ChangeInstanceConnection/hooks/useNotMovedItems/useNotMovedItems.js
- src/components/POLine/ChangeInstanceConnection/hooks/useRelatedItemsMCL/index.js
- src/components/POLine/ChangeInstanceConnection/hooks/useRelatedItemsMCL/useRelatedItemsMCL.js
- src/components/POLine/ChangeInstanceConnection/utils/checkIfSubmitActionProhibited.js
- src/components/POLine/ChangeInstanceConnection/utils/index.js
- src/components/PurchaseOrder/POForm.test.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1290
Since central ordering allows the PO line to have holdings from other tenants, it is necessary to load corresponding data from related tenants.
Implement components and utilities for loading PO line holding items in all related tenants.
https://github.com/folio-org/ui-orders/assets/88109087/fe0d7139-8df6-4910-a0fc-04ef369515df
- Do PRs exist …
> UIOR-1290 ECS - "Change instance" modal adaptation for central ordering enabled

- CHANGELOG.md
- src/settings/RoutingListConfiguration/constants.js
https://folio-org.atlassian.net/browse/UIOR-1287 …
> UIOR-1287 Add title token to printed routing list configuration

- CHANGELOG.md
- src/components/PurchaseOrder/POVersionView/SummaryVersionView/SummaryVersionView.js
- src/components/PurchaseOrder/Summary/SummaryView.js
- translations/ui-orders/en.json
After this PR merged, then information about "Total credited" will be shown. Refs [UIOR-1282](https://folio-org.atlassian.net/browse/UIOR-1282)
> UIOR-1282 Display total credited in composite orders

- CHANGELOG.md
- src/components/POLine/RoutingList/RoutingList.js
> UIOR-1299 Orders app closes after closing Routing list page

- src/common/utils/getPOLineItems.js
https://folio-org.atlassian.net/browse/UIOR-1291 …
> UIOR-1291 Fix PO Line items fetching

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
- src/components/LayerCollection/LayerPOLine.test.js
- translations/ui-orders/en.json
[UIOR-1307](https://folio-org.atlassian.net/browse/UIOR-1307): ECS - handle error message appears when user without appropriate affiliation is trying to edit/open POL with location in such affiliation
https://github.com/user-attachments/assets/f5236ad8-c54d-4362-a0dd-9857a77af9ab
Ideally all of the PRs involved in breaking changes would be merged in the …
> UIOR-1307: ECS - handle error message appears when user without appropriate affiliation is trying to edit/open POL with location in such affiliation

- package.json
> UIOR-1320 User should be able to open orders app without central ordering permission

- CHANGELOG.md
- package.json
Verify changes in permissions
https://folio-org.atlassian.net/browse/UIOR-1316
https://folio-org.atlassian.net/browse/UIOR-1314
Update permissions and interfaces
> UIOR-1316 UIOR-1314 Update permissions and interfaces for `notes` and `consortia-settings`

- CHANGELOG.md
- package.json
> UIOR-1312 clean up ui-orders permissions

- package.json
> Bump up holdings-storange interface

- CHANGELOG.md
- src/OrdersList/OrdersListFilters.js
- src/OrdersList/OrdersListFiltersContainer.js
- src/OrdersList/OrdersListFiltersContainer.test.js
- src/OrdersList/constants.js
- src/OrdersList/hooks/useBuildQuery/useBuildQuery.js
- src/common/utils/buildRelationModifierQuery.js
- src/common/utils/buildRelationModifierQuery.test.js
- src/common/utils/index.js
https://folio-org.atlassian.net/browse/UIOR-1269
https://github.com/user-attachments/assets/626044a2-55a2-4357-a87d-c59cc8770f2e …
> UIOR-1269 Add filter for orders list to search by multiple funds

- CHANGELOG.md
- src/settings/RoutingListConfiguration/RoutingListConfigurationEmailTemplate.js
> UIOR-1340 DOMPurify import is incorrect

- CHANGELOG.md
- src/components/POLine/Location/LocationView.js
https://folio-org.atlassian.net/browse/UIOR-1330
https://github.com/user-attachments/assets/9695013c-e1ef-4b4e-ac72-e610a8fbd914 …
> UIOR-1330 Respect the 'tenantId' property when resolving holdings in central tenant mode

- CHANGELOG.md
- src/OrderLinesList/Details/OrderLineDetails.js
- src/components/POLine/POLine.js
- src/components/POLine/POLine.test.js
- src/components/POLine/POLineActionMenu/POLineActionMenu.js
- src/components/POLine/POLineActionMenu/POLineActionMenu.test.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/getPOActionMenu.js
https://folio-org.atlassian.net/browse/UIREC-424
Toggle Actions menu before redirecting to Receiving app …
> UIOR-1365 Close actions dropdown before navigation to another page

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIOR-1381
https://folio-org.atlassian.net/browse/UIOR-1382
> UIOR-1381 UIOR-1382 Migrate react-intl and stripes dependencies

- CHANGELOG.md
- src/components/LayerCollection/LayerPOLine.js
https://folio-org.atlassian.net/browse/UIOR-1398
> UIOR-1398 Navigate back into an appropriate location after PO Line submit

- CHANGELOG.md
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/const.js
https://folio-org.atlassian.net/browse/UIOR-1372 …
> UIOR-1372 Handle Receiving workflow value on mount

- src/components/POLine/POLineForm.js
> Fix translations via children prop

- CHANGELOG.md
- src/components/POLine/Location/LocationView.js
https://folio-org.atlassian.net/browse/UIOR-1369
https://github.com/user-attachments/assets/c73b4462-9601-4928-a349-323cfbedd88f …
> UIOR-1369 Display empty value instead of 'Invalid link' for affiliation field if no value is assigned to it

- CHANGELOG.md
- src/components/PurchaseOrder/PO.js
https://folio-org.atlassian.net/browse/UIOR-1413
https://github.com/user-attachments/assets/4463dc6c-48c2-4913-8901-61b0e817f646 …
> UIOR-1413 Handle error response on unopen order operation fail

- CHANGELOG.md
- package.json
> Release v8.0.3

- CHANGELOG.md
- src/components/POLine/POLineForm.js
- src/components/POLine/hooks/index.js
- src/components/POLine/hooks/useExpenseClassChange/index.js
- src/components/POLine/hooks/useExpenseClassChange/useExpenseClassChange.js
- src/components/POLine/hooks/useExpenseClassChange/useExpenseClassChange.test.js
- src/components/POLine/utils.js
- translations/ui-orders/en.json
https://folio-org.atlassian.net/browse/UIOR-1406
https://github.com/user-attachments/assets/1cbb0021-ff07-4c61-ba59-e56cf73cdd96 …
> UIOR-1406 Notify a user that an encumbrance is not released from a paid invoice when changing an expense class of an order line

- package.json
> Update settings permission sets to include perm to get `orders-storage/settings`

- src/components/POLine/POLineForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/DonorInformationForm/DonorInformationForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
https://folio-org.atlassian.net/browse/UIOR-1393
https://github.com/user-attachments/assets/aadd9276-b8e1-4097-a0c2-afa1f49db67a …
> UIOR-1393 Fix an issue with populating donors template value in the PO Line form

- CHANGELOG.md
- src/components/POLine/Item/ContributorForm.js
- src/components/POLine/Item/ItemForm.js
- src/components/POLine/Item/ItemView.js
- src/components/POLine/Item/ProductIdDetailsForm.js
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/POLine/POLineForm.js
- src/components/POLine/POLineView.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsForm.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POForm.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditor.js
- src/settings/OrderTemplates/OrderTemplatesEditor/OrderTemplatesEditorContainer.js
https://folio-org.atlassian.net/browse/UIOR-1394
Use `<VisibilityControl>` to configure _hiding_ property in the template, `<IfFieldVisible>` for fields and form accordions (will remain them visible if there are validation errors), and `<IfVisible>` for view components.
https://github.com/user-attachments/assets/a8929342-ac31-4e4e-ba1c-f181362f5fd3
Ideally …
> UIOR-1394 Add ability to hide optional fields in the order template form

- CHANGELOG.md
- src/common/POFields/OngoingInfoFields/FieldRenewalDate.js
- src/components/PurchaseOrder/OngoingOrderInfo/OngoingInfoForm.js
- src/components/PurchaseOrder/OngoingOrderInfo/OngoingInfoForm.test.js
https://folio-org.atlassian.net/browse/UIOR-1426
https://github.com/user-attachments/assets/3e989403-b6ae-43d4-a83b-8a2ddcc60511 …
> UIOR-1426 Disable the 'Subscription' checkbox in the PO form when an order workflow status is 'Open'

- CHANGELOG.md
- package.json
Full changes https://github.com/folio-org/ui-orders/compare/v7.0.4..UIOR-1441
> Release v7.0.5

- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/POVersionView/PODetailsVersionView/PODetailsVersionView.js
- src/components/PurchaseOrder/util.js
https://folio-org.atlassian.net/browse/UIOR-1403
> UIOR-1403 Display opened year both for opened and closed order

- CHANGELOG.md
- package.json
Update for Split Search & Browse APIs
https://folio-org.atlassian.net/browse/UIOR-1452
Update interfaces …
> UIOR-1452 Update for Split Search & Browse APIs

- CHANGELOG.md
- src/components/POLine/RelatedInvoiceLines/constants.js
https://folio-org.atlassian.net/browse/UIOR-1458
Refer to the correct field in sorters.
https://github.com/user-attachments/assets/0715c983-bd36-4d84-81d6-166c08a146fa …
> UIOR-1458 Sort PO Line related invoice lines by invoice date

- CHANGELOG.md
- src/components/POLine/Location/LocationForm.js
- src/components/POLine/Location/LocationForm.test.js
- src/components/POLine/hooks/index.js
- src/components/POLine/hooks/usePOLinePiecesExistence/index.js
- src/components/POLine/hooks/usePOLinePiecesExistence/usePOLinePiecesExistence.js
- src/components/POLine/hooks/usePOLinePiecesExistence/usePOLinePiecesExistence.test.js
- src/components/POLine/utils.js
- src/components/POLine/utils.test.js
https://folio-org.atlassian.net/browse/UIOR-1418
After changing location in unopen order with a "Synchronized order and receipt quantity" workflow, when one related item was received, the order cannot be opened due to a conflict with deleting last piece, resulting in an endless displaying “Piece(s) to be deleted” modal. 
Check for received pieces related to a PO Line of the `Pending` PO with "synchronized" receiving workflow.
https://github.com/user-attachments/assets/550f58a6-6e5a-437d-bd77-81c3b07f79e1
- What other modules …
> UIOR-1418 Prevent editing locations for pending 'synchronized' PO Line with related received pieces

- CHANGELOG.md
- src/components/POLine/POLineDetails/POLineDetailsForm.js
- src/components/PurchaseOrder/PO.js
- src/components/PurchaseOrder/PODetails/PODetailsView.js
- src/components/PurchaseOrder/PODetails/PODetailsView.test.js
- src/components/PurchaseOrder/POVersionView/PODetailsVersionView/PODetailsVersionView.js
- src/components/PurchaseOrder/hooks/usePurchaseOrderResources/usePurchaseOrderResources.js
- src/components/PurchaseOrder/hooks/useSelectedPOVersion/useSelectedPOVersion.js
https://folio-org.atlassian.net/browse/UIOR-1456
Currently, Approved By and Opened By can be exported, but cannot be viewed in record view. The approver and opener should be displayed next to the respective approved and opened dates.
https://github.com/user-attachments/assets/97c76368-bdf2-4bf2-964d-be1e080c21ea
> UIOR-1456 Add 'Approved by' and 'Opened by'  to order view and order history view
